'use strict';
const $=selector=>document.querySelector(selector);
const languages={en:'English',fr:'Français',de:'Deutsch',es:'Español'};
const labels={name:'Ürün adı / H1',lead:'Kısa giriş',heading:'İçerik başlığı',paragraph1:'Ürün anlatımı',paragraph2:'İkinci paragraf',metaTitle:'SEO başlığı',metaDescription:'Meta açıklama',question:'Ürüne özel soru',answer:'Yanıt',specs:'Özellikler — her satır: Başlık|Açıklama',imageAlt:'Görsel alt metni'};
const limits={name:120,lead:700,heading:200,paragraph1:4000,paragraph2:4000,metaTitle:180,metaDescription:500,question:500,answer:2500,specs:2000,imageAlt:250};
let csrf='',doc=null,version=0,current=0,language='en',dirty=false,busy=false,loadedSlugs=new Set();
function node(tag,text,attrs={}){const e=document.createElement(tag);if(text!==null)e.textContent=text;for(const[k,v]of Object.entries(attrs))e.setAttribute(k,v);return e;}
function message(text,error=false){$('#status').textContent=text;$('#status').classList.toggle('error',error);}
function revision(){const active=doc.products.filter(p=>p.active).length;$('#revision').textContent=`Sürüm ${version} · ${active} aktif ürün · ${dirty?'Kaydedilmemiş değişiklikler':'Taslak güncel'}`;$('#revision').classList.toggle('dirty',dirty);}
function changed(product){dirty=true;if(product)product.updated=new Date().toISOString().slice(0,10);revision();}
async function request(action,body){const r=await fetch('/api/admin?action='+action,{method:body===undefined?'GET':'POST',credentials:'same-origin',headers:body===undefined?{}:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:body===undefined?undefined:JSON.stringify(body)});const value=await r.json();if(!r.ok){if(r.status===401){$('#workspace').hidden=true;$('#login').hidden=false;$('#logout').hidden=true;doc=null;csrf='';}throw new Error(value.error||'İşlem tamamlanamadı.');}return value;}
async function task(work){if(busy)return;busy=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);try{await work();}catch(e){message(e.message,true);}finally{busy=false;document.querySelectorAll('button').forEach(b=>b.disabled=false);}}
function field(parent,label,value,onChange,{multiline=false,max=6000,type='text',readonly=false}={}){const wrap=node('label',label);const input=node(multiline?'textarea':'input',null,{maxlength:String(max)});if(!multiline)input.type=type;input.value=value;input.readOnly=readonly;input.addEventListener('input',()=>onChange(input.value));wrap.append(input);parent.append(wrap);return wrap;}
function check(parent,label,value,onChange){const wrap=node('label',null),input=node('input',null,{type:'checkbox'});input.checked=value;input.addEventListener('change',()=>onChange(input.checked));wrap.append(input,document.createTextNode(label));parent.append(wrap);}
function tabs(parent,onSelect){const bar=node('div',null,{class:'tabs'});for(const [code,name]of Object.entries(languages)){const b=node('button',name,{type:'button',class:code===language?'active':''});b.addEventListener('click',()=>{language=code;onSelect();});bar.append(b);}parent.append(bar);}
function list(){const root=$('#product-list');root.replaceChildren();doc.products.forEach((p,i)=>{const b=node('button',null,{type:'button',class:'product-button'});if(i===current)b.setAttribute('aria-current','true');b.append(node('img',null,{src:p.image,alt:'',loading:'lazy'}));const text=node('span',p.locales.en.name||'Yeni ürün');text.append(node('small',p.active?'AKTİF · '+p.slug:'PASİF · '+p.slug));b.append(text);b.addEventListener('click',()=>{current=i;list();editor();});root.append(b);});}
function editor(){const p=doc.products[current],root=$('#product-editor');root.replaceChildren();root.append(node('h2',p.locales[language].name||'Yeni ürün'));const common=node('div',null,{class:'field-grid'});
 field(common,'Kalıcı ürün adresi (küçük harf ve tire)',p.slug,v=>{p.slug=v;changed(p);},{max:80,readonly:loadedSlugs.has(p.slug)});
 const category=node('label','Koleksiyon'),select=node('select',null);['Ev tekstili','Otel & spa','Bebek'].forEach((name,i)=>{const option=node('option',name,{value:String(i)});select.append(option);});select.value=p.group;select.addEventListener('change',()=>{p.group=Number(select.value);changed(p);});category.append(select);common.append(category);root.append(common);
 check(root,'Koleksiyonda ve ürün sayfasında yayınla',p.active,v=>{p.active=v;changed(p);list();});
 const images=node('div',null,{class:'image-fields'}),preview=node('img',null,{class:'image-preview',src:p.image,alt:p.locales[language].imageAlt});images.append(preview);const upload=node('div',null);const label=node('label','Yeni ürün görseli (JPEG, PNG, WebP · en fazla 2 MB)'),file=node('input',null,{type:'file',accept:'image/jpeg,image/png,image/webp'});file.addEventListener('change',()=>task(async()=>{const selected=file.files[0];if(!selected)return;if(selected.size>2100000)throw new Error('Görsel en fazla 2 MB olabilir.');const encoded=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(selected);});message('Görsel işleniyor; metadata temizlenip WebP olarak saklanacak…');const result=await request('image',{base64:encoded});p.image=result.path;p.realPhoto=true;changed(p);preview.src=result.path;list();message('Görsel yüklendi. Taslağı kaydetmeyi unutmayın.');}));label.append(file);upload.append(label);check(upload,'Görsel gerçek ürün fotoğrafıdır',p.realPhoto,v=>{p.realPhoto=v;changed(p);});upload.append(node('p','Yükleme canlı görseli değiştirmez. Yeni görsel yayını onayladığınızda kullanılır.',{class:'muted'}));images.append(upload);root.append(images);tabs(root,editor);
 const fields=node('div',null,{class:'field-grid'});for(const[key,label]of Object.entries(labels)){const multiline=!['name','heading','metaTitle','imageAlt'].includes(key);const wrap=field(fields,label,p.locales[language][key],value=>{p.locales[language][key]=value;changed(p);},{multiline,max:limits[key]});if(multiline)wrap.className='wide';}root.append(fields);root.append(node('p','Dört dilin tümünü doldurun. HTML kullanılmaz; içerikler güvenli düz metin olarak yayınlanır.',{class:'muted'}));}
function settings(){const root=$('#settings');root.replaceChildren(node('h2','Firma ve iletişim bilgileri'));const form=node('div',null,{class:'settings-form'});for(const[key,label]of Object.entries({address:'Fabrika adresi',phone:'Telefon (ülke koduyla: +90…)',email:'İletişim e-postası',founded:'Kuruluş yılı'}))field(form,label,doc.settings[key],v=>{doc.settings[key]=v;changed();},{max:key==='address'?500:key==='email'?254:key==='founded'?4:40});form.append(node('p','Yayın sonrası footer, iletişim bağlantıları ve yapılandırılmış firma verileri güncellenir. E-posta adresini değiştirmek mail hizmetinin şifresini veya teslimat ayarlarını değiştirmez.',{class:'muted'}));root.append(form);}
function pages(){const root=$('#pages');root.replaceChildren(node('h2','Sayfa başlıkları ve içerikleri'));tabs(root,pages);for(const[slug,page]of Object.entries(doc.pages[language])){const box=node('div',null,{class:'page-editor'});box.append(node('h2',{'home':'Ana sayfa','about':'Hakkımızda','sourcing-guide':'Satın alma rehberi','contact':'İletişim'}[slug]));for(const[key,label]of Object.entries({title:'SEO başlığı',description:'Meta açıklama',heading:'Ana başlık',intro:'Giriş metni'}))field(box,label,page[key],v=>{page[key]=v;changed();},{multiline:key==='intro'||key==='description',max:key==='intro'?6000:500});box.append(node('p','Boş bırakılan alan mevcut özgün içeriği korur.',{class:'muted'}));root.append(box);}}
async function enquiries(){const root=$('#enquiries');root.replaceChildren(node('h2','Müşteri teklif kutusu'));const rows=await request('enquiries');if(!rows.length)root.append(node('p','Henüz kaydedilmiş talep yok. Çift teslimat, mail bağlantısı kurulduktan sonra etkinleşir.'));for(const row of rows){const card=node('article',null,{class:'enquiry'});card.append(node('h2',row.payload.customerName||'Müşteri talebi'),node('p',new Date(row.created_at).toLocaleString('tr-TR')+' · Mail: '+({pending:'bekliyor',sent:'gönderildi',failed:'teslim edilemedi'}[row.mail_status]||'bilinmiyor')));for(const key of ['companyName','email','phone','notes','items'])if(row.payload[key])card.append(node('pre',String(row.payload[key])));if(!row.read_at){const b=node('button','Okundu olarak işaretle');b.addEventListener('click',()=>task(async()=>{await request('read-enquiry',{id:row.id});await enquiries();}));card.append(b);}root.append(card);}}
async function load(){const data=await request('content');doc=data.payload;version=data.version;loadedSlugs=new Set(doc.products.map(p=>p.slug));dirty=false;current=Math.min(current,doc.products.length-1);list();editor();settings();pages();revision();message('Taslak yüklendi. Canlı site yalnızca yayın onayından sonra değişir.');}
async function boot(){const status=await request('status');csrf=status.csrf||'';$('#workspace').hidden=!status.authenticated;$('#login').hidden=status.authenticated;$('#logout').hidden=!status.authenticated;if(status.authenticated)await load();else{message(status.configured?'Yönetici hesabınızla giriş yapın.':'Panel hazır, güvenli bağlantı kurulmayı bekliyor. Supabase ve Vercel ayarları tamamlanmadan giriş açılamaz.',!status.configured);$('#login-form button').disabled=!status.configured;}}
document.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>task(async()=>{if(!doc)return;document.querySelectorAll('.view').forEach(v=>v.hidden=v.id!==button.dataset.view);document.querySelectorAll('[data-view]').forEach(b=>b.removeAttribute('aria-current'));button.setAttribute('aria-current','page');if(button.dataset.view==='enquiries')await enquiries();})));
$('#login-form').addEventListener('submit',e=>{e.preventDefault();task(async()=>{const form=new FormData(e.target);await request('login',{email:form.get('email'),password:form.get('password')});e.target.reset();await boot();});});
$('#product-editor').addEventListener('submit',e=>e.preventDefault());
$('#logout').addEventListener('click',()=>task(async()=>{if(dirty&&!confirm('Kaydedilmemiş değişiklikler var. Çıkılsın mı?'))return;await request('logout',{});doc=null;dirty=false;await boot();}));
$('#reload').addEventListener('click',()=>task(async()=>{if(dirty&&!confirm('Kaydedilmemiş değişiklikler silinecek. Yeniden yüklensin mi?'))return;await load();}));
$('#save').addEventListener('click',()=>task(async()=>{const result=await request('save',{payload:doc,version});version=result.version;loadedSlugs=new Set(doc.products.map(p=>p.slug));dirty=false;revision();message('Taslak güvenli veritabanına kaydedildi. Canlı site değişmedi.');}));
$('#add-product').addEventListener('click',()=>{if(!doc)return;const locales={};for(const code of Object.keys(languages)){locales[code]={};for(const key of Object.keys(labels))locales[code][key]='';}doc.products.push({slug:'new-product-'+Date.now(),group:0,active:false,image:'/img/products/towels.webp',realPhoto:false,updated:new Date().toISOString().slice(0,10),locales});current=doc.products.length-1;changed();list();editor();});
$('#review').addEventListener('click',()=>{$('#publish-summary').textContent=`${doc.products.filter(p=>p.active).length} aktif ürün · 4 dil · iletişim ve sayfa bilgileri. ${dirty?'Kaydedilmemiş değişiklikler de bu yayın isteğine dahildir.':''}`;$('#publish-dialog').showModal();});
$('#cancel-publish').addEventListener('click',()=>$('#publish-dialog').close());
$('#publish').addEventListener('click',()=>task(async()=>{const result=await request('publish',{payload:doc,version});version=result.version;dirty=false;revision();$('#publish-dialog').close();message('Yayın isteği gönderildi. GitHub kontrolleri ve Vercel dağıtımı tamamlandığında içerik canlıya geçer.');}));
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
boot().catch(e=>message(e.message,true));
