from pathlib import Path
from html import escape as esc
import json, shutil
from multilingual_seo import enrich, write_sitemap, COPY
from editorial_content import CORE, FACTS, PRODUCTS as EDITORIAL_PRODUCTS, apply_voice, UPDATED, FOUNDED, DATES
from connection_band import connection_band
from buyer_experience import enhance
from hero_design import refine_hero
from product_seo import enrich_product, UPDATED as SEO_UPDATED, DATES as SEO_DATES

ROOT = Path(__file__).resolve().parents[1]
DOMAIN = 'https://www.tvstextile.com'
ADDRESS = 'Akçeşme M. 2605 Sk. No: 40 Merkezefendi, Denizli, Türkiye'
ITEMS = [
 ('muslin-duvet-covers',0,'Muslin duvet covers','Gaze de coton housse de couette','Musselin Bettwäsche','Fundas nórdicas de muselina','A relaxed texture for thoughtfully designed bedrooms.','Discuss the fabric composition, gauze layers and finished dimensions. Confirm shrinkage expectations and washing instructions before placing an order.'),
 ('fitted-sheets',0,'Fitted sheets','Drap housse','Spannbettlaken','Sábanas bajeras','The foundation of a comfortable bed.','Share the mattress width, length and depth, along with your preferred fabric. Elastic placement and fit should be agreed against your mattress dimensions.'),
 ('duvet-covers',0,'Duvet covers','Housse de couette','Bettbezüge','Fundas nórdicas','Bedding that brings a collection together.','Specify duvet dimensions, fabric composition, closure type and pillowcase requirements. Send a colour reference or design brief for a coordinated bedding enquiry.'),
 ('bathrobes',1,'Bathrobes','Peignoir','Bademäntel','Albornoces','Comfort beyond the room.','Discuss robe style, size range, fabric weight and belt details. For hospitality use, include your laundering conditions and any embroidery requirements in the enquiry.'),
 ('towels',1,'Towels','Serviettes de bain','Handtücher','Toallas','Everyday essentials. A considered finish.','Specify towel dimensions, fabric composition, weight in GSM and colour. Include your intended use, laundering requirements and desired quantities for each size.'),
 ('sauna-wraps',1,'Sauna wraps','Kilts de sauna','Saunakilts','Pareos de sauna','Textiles for moments of wellbeing.','Share the required length, waist range and preferred fastening. Fabric weight, absorbency requirements and spa laundering conditions help define the brief.'),
 ('spa-headbands',1,'Spa headbands','Bandeaux de spa','Spa Stirnbänder','Diademas de spa','Small details for a complete spa collection.','Confirm the width, head circumference range and preferred fastening or elastic fit. Include your intended treatment use and laundering conditions.'),
 ('makeup-remover-cloths',1,'Makeup remover cloths','Lingettes démaquillantes','Abschminktücher','Toallitas desmaquillantes','A thoughtful addition to daily routines.','Discuss cloth dimensions, textile composition and surface texture. Confirm care instructions, pack quantities and intended use before approving specifications.'),
 ('baby-ponchos',2,'Baby ponchos','Ponchos bébé','Baby Ponchos','Ponchos para bebé','Wrap little moments in comfort.','Share the intended age range, finished dimensions and hood requirements. Discuss fabric, care instructions and destination-market requirements before ordering.'),
 ('baby-swaddles',2,'Baby swaddles','Langes bébé','Baby Pucktücher','Muselinas para bebé','Soft textiles for a carefully considered baby range.','Specify dimensions, composition and print or colour preferences. Product instructions and applicable destination-market requirements need to be agreed for the intended use.'),
 ('baby-sleeping-bags',2,'Baby sleeping bags','Gigoteuses bébé','Baby Schlafsäcke','Sacos de dormir para bebé','Designed around your baby collection brief.','Provide the intended age and size range, seasonal use and fastening preferences. Thermal ratings and applicable safety testing must be verified for the final product; they are not assumed.'),
 ('baby-comforters',2,'Baby comforters','Doudou','Baby Schmusetücher','Dou dou para bebé','A tactile detail for baby collections.','Discuss dimensions, fabric and attachment details. Intended age, labelling and applicable safety requirements must be reviewed for the final design and destination market.')
]
L = {
 'en':dict(nav=['Collections','Our company','Sourcing guide','Contact'],cta='Discuss your project',groups=['Home textiles','Hotel & spa','Baby textiles'],tag='TEXTILES FROM DENİZLİ, TÜRKİYE',hero='Woven for everyday.<br><em>Made for your world.</em>',intro='Home, hospitality and baby textiles for international buyers. Discover the collection. Tell us what you have in mind.',explore='Explore collections',collection='A world of textures.',collection_sub='Three collections. One considered approach to textiles.',detail='Explore the range',project='Your next collection<br><em>starts with a conversation.</em>',project_sub='Tell us about your products, quantities and destination. Let’s shape the next step together.',spec='Build your product brief',related='Explore the collection',back='All collections',inquiry='Enquire about this product',buyer='For international buyers',note='These generated concept visuals illustrate the product category. Ask us for current product photographs, samples and specifications.',brief='For a relevant quotation, share your quantities, dimensions, material preferences, destination and target schedule.',footer='Textiles for living.<br>Partnerships for growing.',contact='Contact',about='Our company',guide='Sourcing guide',home='Home',lang='Language'),
 'fr':dict(nav=['Collections','Notre entreprise','Guide d’achat','Contact'],cta='Parlons de votre projet',groups=['Linge de maison','Hôtel & spa','Textiles bébé'],tag='TEXTILES DE DENİZLİ, TÜRKİYE',hero='Tissés pour le quotidien.<br><em>Pensés pour votre univers.</em>',intro='Linge de maison, textiles pour l’hôtellerie et articles bébé pour les acheteurs internationaux. Découvrez nos collections et partagez votre projet.',explore='Découvrir les collections',collection='Un univers de textures.',collection_sub='Trois collections. Une approche attentive du textile.',detail='Découvrir la gamme',project='Votre prochaine collection<br><em>commence par un échange.</em>',project_sub='Présentez vos produits, quantités et destination. Préparons ensemble la prochaine étape.',spec='Préparez votre cahier des charges',related='Découvrez la collection',back='Toutes les collections',inquiry='Demander des informations',buyer='Pour les acheteurs internationaux',note='Ces visuels de concept générés illustrent la catégorie de produits. Demandez les photographies, échantillons et spécifications des produits actuels.',brief='Pour un devis adapté, précisez les quantités, dimensions, matières, destination et calendrier souhaité.',footer='Des textiles pour vivre.<br>Des partenariats pour grandir.',contact='Contact',about='Notre entreprise',guide='Guide d’achat',home='Accueil',lang='Langue'),
 'de':dict(nav=['Kollektionen','Unternehmen','Einkaufsleitfaden','Kontakt'],cta='Ihr Projekt besprechen',groups=['Heimtextilien','Hotel & Spa','Babytextilien'],tag='TEXTILIEN AUS DENİZLİ, TÜRKİYE',hero='Für den Alltag gewebt.<br><em>Für Ihre Welt gemacht.</em>',intro='Heimtextilien, Hoteltextilien und Babytextilien für internationale Einkäufer. Entdecken Sie die Kollektionen und erzählen Sie uns von Ihrem Projekt.',explore='Kollektionen entdecken',collection='Eine Welt voller Texturen.',collection_sub='Drei Kollektionen. Ein durchdachter Ansatz für Textilien.',detail='Sortiment entdecken',project='Ihre nächste Kollektion<br><em>beginnt mit einem Gespräch.</em>',project_sub='Teilen Sie uns Produkte, Mengen und Zielland mit. Gemeinsam besprechen wir den nächsten Schritt.',spec='Ihre Produktspezifikation',related='Kollektion entdecken',back='Alle Kollektionen',inquiry='Produkt anfragen',buyer='Für internationale Einkäufer',note='Diese generierten Konzeptbilder veranschaulichen die Produktkategorie. Fragen Sie nach aktuellen Produktfotos, Mustern und Spezifikationen.',brief='Für ein passendes Angebot nennen Sie Mengen, Maße, Materialwünsche, Zielland und gewünschten Zeitplan.',footer='Textilien zum Leben.<br>Partnerschaften zum Wachsen.',contact='Kontakt',about='Unternehmen',guide='Einkaufsleitfaden',home='Startseite',lang='Sprache'),
 'es':dict(nav=['Colecciones','Empresa','Guía de compra','Contacto'],cta='Hablemos de su proyecto',groups=['Textiles para el hogar','Hotel & spa','Textiles para bebé'],tag='TEXTILES DE DENİZLİ, TÜRKİYE',hero='Tejidos para cada día.<br><em>Pensados para su mundo.</em>',intro='Textiles para el hogar, hostelería y bebé para compradores internacionales. Descubra las colecciones y comparta su proyecto.',explore='Explorar colecciones',collection='Un mundo de texturas.',collection_sub='Tres colecciones. Una forma cuidada de entender los textiles.',detail='Explorar la gama',project='Su próxima colección<br><em>empieza con una conversación.</em>',project_sub='Cuéntenos sus productos, cantidades y destino. Preparemos juntos el siguiente paso.',spec='Prepare su ficha de producto',related='Explorar la colección',back='Todas las colecciones',inquiry='Consultar este producto',buyer='Para compradores internacionales',note='Estas imágenes conceptuales generadas ilustran la categoría de productos. Solicite fotografías actuales, muestras y especificaciones de los productos.',brief='Para un presupuesto adecuado, indique cantidades, medidas, materiales, destino y calendario deseado.',footer='Textiles para vivir.<br>Alianzas para crecer.',contact='Contacto',about='Empresa',guide='Guía de compra',home='Inicio',lang='Idioma')
}
GROUP_SLUGS=['home-textiles','hotel-spa-textiles','baby-textiles']
for language in L:
 L[language]['intro']=FACTS[language]['intro']
 L[language]['brief']=CORE[language]['brief']
 L[language]['project_sub']=CORE[language]['contact']
IMAGES=['products/muslin-duvet-covers.webp','products/towels.webp','products/baby-ponchos.webp']
LABEL_INDEX={'en':2,'fr':3,'de':4,'es':5}
DETAILS={
 'fr':[
 'Précisez la composition, le nombre de couches de gaze et les dimensions finies. Convenez du retrait attendu et des instructions de lavage avant la commande.',
 'Indiquez la largeur, la longueur et la hauteur du matelas ainsi que la matière souhaitée. La position des élastiques et l’ajustement doivent correspondre au matelas.',
 'Précisez les dimensions, la composition, le type de fermeture et les taies souhaitées. Ajoutez une référence de couleur ou un dessin pour une collection coordonnée.',
 'Discutez du style, des tailles, du grammage et de la ceinture. Pour l’hôtellerie, précisez les conditions de lavage et les besoins de broderie.',
 'Indiquez les dimensions, la composition, le grammage en GSM et les couleurs. Précisez l’usage, les conditions de lavage et les quantités par taille.',
 'Précisez la longueur, le tour de taille et la fermeture souhaitée. Ajoutez le grammage, les besoins d’absorption et les conditions de lavage du spa.',
 'Confirmez la largeur, le tour de tête et la fermeture ou l’élastique. Précisez les soins prévus et les conditions de lavage.',
 'Discutez des dimensions, de la composition et de la texture. Confirmez l’entretien, les quantités par lot et l’usage avant validation.',
 'Indiquez l’âge prévu, les dimensions et les détails de la capuche. Discutez de la matière, de l’entretien et des exigences du marché de destination.',
 'Précisez les dimensions, la composition et les motifs ou couleurs. Les instructions et exigences applicables doivent être convenues selon l’usage prévu.',
 'Indiquez l’âge, les tailles, la saison et les fermetures. Les indices thermiques et essais de sécurité doivent être vérifiés pour le produit final et ne sont pas présumés.',
 'Discutez des dimensions, matières et éléments attachés. L’âge prévu, l’étiquetage et les exigences de sécurité doivent être examinés pour le modèle final et le marché visé.'
 ],
 'de':[
 'Nennen Sie Zusammensetzung, Anzahl der Musselinlagen und Fertigmaße. Klären Sie Einlaufverhalten und Waschanleitung vor der Bestellung.',
 'Nennen Sie Breite, Länge und Höhe der Matratze sowie das gewünschte Material. Gummizug und Passform müssen auf die Matratzenmaße abgestimmt werden.',
 'Geben Sie Maße, Zusammensetzung, Verschluss und Kissenbezüge an. Farbvorlagen oder Designs helfen bei einer abgestimmten Bettwäschekollektion.',
 'Besprechen Sie Schnitt, Größen, Stoffgewicht und Gürtel. Für Hotels nennen Sie Waschbedingungen und gewünschte Stickereien.',
 'Nennen Sie Maße, Zusammensetzung, Gewicht in GSM und Farbe. Ergänzen Sie Verwendungszweck, Waschbedingungen und Mengen je Größe.',
 'Nennen Sie Länge, Taillenumfang und Verschluss. Stoffgewicht, Saugfähigkeitsanforderungen und Waschbedingungen definieren den Bedarf.',
 'Bestätigen Sie Breite, Kopfumfang und Verschluss oder elastische Passform. Beschreiben Sie Behandlungszweck und Waschbedingungen.',
 'Besprechen Sie Maße, Zusammensetzung und Oberflächenstruktur. Pflegehinweise, Packmengen und Verwendungszweck sind vor der Freigabe zu klären.',
 'Nennen Sie Altersgruppe, Maße und Kapuzendetails. Klären Sie Material, Pflege und Anforderungen des Zielmarktes vor der Bestellung.',
 'Nennen Sie Maße, Zusammensetzung und Druck- oder Farbwünsche. Gebrauchshinweise und geltende Anforderungen müssen für die vorgesehene Nutzung vereinbart werden.',
 'Nennen Sie Alters- und Größenbereich, Saison und Verschlüsse. Wärmewerte und Sicherheitsprüfungen müssen für das Endprodukt verifiziert werden und werden nicht vorausgesetzt.',
 'Besprechen Sie Maße, Material und Befestigungsdetails. Alter, Kennzeichnung und geltende Sicherheitsanforderungen müssen für das Enddesign und den Zielmarkt geprüft werden.'
 ],
 'es':[
 'Indique composición, capas de muselina y medidas finales. Confirme el encogimiento previsto y las instrucciones de lavado antes del pedido.',
 'Indique ancho, largo y altura del colchón y el tejido deseado. La posición del elástico y el ajuste deben acordarse según esas medidas.',
 'Especifique medidas, composición, cierre y fundas de almohada. Comparta referencias de color o diseño para una colección coordinada.',
 'Comente estilo, tallas, gramaje y cinturón. Para hoteles, incluya condiciones de lavado y requisitos de bordado.',
 'Indique medidas, composición, gramaje en GSM y colores. Incluya uso previsto, lavado y cantidades por tamaño.',
 'Indique longitud, contorno de cintura y cierre. Gramaje, absorción y lavado del spa ayudan a definir la ficha.',
 'Confirme ancho, contorno de cabeza y cierre o ajuste elástico. Indique el tratamiento previsto y las condiciones de lavado.',
 'Comente medidas, composición y textura. Confirme cuidados, unidades por paquete y uso antes de aprobar las especificaciones.',
 'Indique edad prevista, medidas y detalles de capucha. Comente tejido, cuidados y requisitos del mercado de destino.',
 'Especifique medidas, composición y estampados o colores. Las instrucciones y requisitos aplicables deben acordarse para el uso previsto.',
 'Indique edades, tallas, temporada y cierres. Los valores térmicos y ensayos de seguridad deben verificarse para el producto final; no se presuponen.',
 'Comente medidas, tejidos y accesorios. Edad, etiquetado y requisitos de seguridad deben revisarse para el diseño final y el mercado de destino.'
 ]}

def write(path,text):
 p=ROOT/path; p.parent.mkdir(parents=True,exist_ok=True); p.write_text(text,encoding='utf-8')
def route(lang,slug='index'):
 return ('' if lang=='en' else lang+'/') + ('' if slug=='index' else slug+'.html')
def local(lang,slug='index'):
 return ('' if lang=='en' else lang+'/') + slug+'.html'
def image(group,base='',eager=False):
 attr='fetchpriority="high"' if eager else 'loading="lazy"'
 return f'<img src="{base}img/{IMAGES[group]}" alt="{["Bedroom textile collection","Hospitality and spa collection","Baby textile collection"][group]}" width="1600" height="1067" {attr} decoding="async">'
def product_image(slug,lang,base='',eager=False):
 name=next(it[LABEL_INDEX[lang]] for it in ITEMS if it[0]==slug)
 qualifier={'en':'illustrative product visual','fr':'visuel illustratif du produit','de':'illustrative Produktdarstellung','es':'imagen ilustrativa del producto'}[lang]
 attr='fetchpriority="high"' if eager else 'loading="lazy"'
 return f'<img src="{base}img/products/{slug}.webp" srcset="{base}img/products/{slug}-768.webp 768w, {base}img/products/{slug}.webp 1536w" sizes="(max-width:760px) 88vw, (max-width:1100px) 44vw, 40vw" alt="{esc(name+" — "+qualifier,quote=True)}" width="1536" height="1024" {attr} decoding="async">'
def cards(lang,base='',group=None,exclude=None):
 t=L[lang]; out=''
 for i,it in enumerate(ITEMS):
  if group is not None and it[1]!=group: continue
  if it[0]==exclude: continue
  out+=f'<a class="product-tile reveal" href="{base}{local(lang,"collections/"+it[0])}"><div class="product-photo">{product_image(it[0],lang,base)}<span class="tile-number">{i+1:02}</span></div><div class="product-caption"><div><span class="eyebrow">{t["groups"][it[1]]}</span><h3>{it[LABEL_INDEX[lang]]}</h3></div><span class="arrow" aria-hidden="true">↗</span></div></a>'
 return out
def groups(lang,base):
 t=L[lang]
 return '<div class="collection-grid">'+''.join(f'<a class="collection-card reveal" href="{base}{local(lang,"collections/"+slug)}"><div class="collection-image">{image(i,base)}<span class="image-index">0{i+1} / COLLECTION</span></div><div class="collection-caption"><h3>{t["groups"][i]}</h3><span aria-hidden="true">↗</span></div><p>{" · ".join(it[LABEL_INDEX[lang]] for it in ITEMS if it[1]==i)}</p></a>' for i,slug in enumerate(GROUP_SLUGS))+'</div>'
def page(lang,slug,title,description,body,noindex=False):
 t=L[lang]; file=local(lang,slug); depth=len(Path(file).parts)-1; base='/' if slug=='404' else '../'*depth
 body=apply_voice(lang,slug,body,ITEMS,LABEL_INDEX)
 canonical=DOMAIN+'/'+route(lang,slug)
 multilingual = not noindex and slug not in ['privacy','blog']
 alternates=''.join(f'<link rel="alternate" hreflang="{code}" href="{DOMAIN}/{route(code,slug)}">' for code in L) if multilingual else ''
 if alternates: alternates+=f'<link rel="alternate" hreflang="x-default" href="{DOMAIN}/{route("en",slug)}">'
 schema={'@context':'https://schema.org','@graph':[{'@type':'Organization','@id':DOMAIN+'/#organization','name':'TVS Textile','url':DOMAIN,'logo':DOMAIN+'/img/tvslogo_yeni.webp','email':'ozkan@tvstextile.com','telephone':'+905324770375','address':{'@type':'PostalAddress','streetAddress':'Akçeşme M. 2605 Sk. No: 40','addressLocality':'Merkezefendi','addressRegion':'Denizli','addressCountry':'TR'}},{'@type':'WebPage','@id':canonical+'#webpage','url':canonical,'name':title,'description':description,'inLanguage':lang,'publisher':{'@id':DOMAIN+'/#organization'}}]}
 if slug=='index': schema['@graph'].append({'@type':'WebSite','@id':DOMAIN+'/#website','url':DOMAIN,'name':'TVS Textile','publisher':{'@id':DOMAIN+'/#organization'},'inLanguage':['en','fr','de','es']})
 if slug=='products' or slug.startswith('collections/') and slug.split('/')[-1] in GROUP_SLUGS:
  subset=ITEMS if slug=='products' else [it for it in ITEMS if it[1]==GROUP_SLUGS.index(slug.split('/')[-1])]
  schema['@graph'][1]['@type']='CollectionPage'
  schema['@graph'].append({'@type':'ItemList','itemListElement':[{'@type':'ListItem','position':i+1,'name':it[LABEL_INDEX[lang]],'url':DOMAIN+'/'+route(lang,'collections/'+it[0])} for i,it in enumerate(subset)]})
 if slug!='index': schema['@graph'].append({'@type':'BreadcrumbList','itemListElement':[{'@type':'ListItem','position':1,'name':t['home'],'item':DOMAIN+'/'+route(lang)},{'@type':'ListItem','position':2,'name':title.split(' | ')[0],'item':canonical}]})
 title,description,body=enrich(lang,slug,title,description,body,base,t,ITEMS,GROUP_SLUGS,LABEL_INDEX,local,DOMAIN,route,schema,noindex,DETAILS)
 title,description,body=enrich_product(lang,slug,title,description,body,ITEMS,LABEL_INDEX,base,local)
 product_updated=slug.startswith('collections/') and slug.split('/')[-1] in [it[0] for it in ITEMS]
 page_updated=SEO_UPDATED if product_updated else UPDATED
 for node in schema['@graph']:
  if node['@type']=='Organization':
   node['foundingDate']=FOUNDED
   node['description']=FACTS[lang]['about']
  if node['@type'] in ['WebPage','CollectionPage']:
   node.update(name=title,description=description)
   node['dateModified']=page_updated
   node['author']={'@id':DOMAIN+'/#organization'}
 if not noindex:
  dateline=f'<div class="content-meta"><span>{esc(CORE[lang]["by"])}</span><time datetime="{page_updated}">{SEO_DATES[lang] if product_updated else DATES[lang]}</time></div>'
  body=body.replace('</section>','</section>'+dateline,1) if slug=='index' else body.replace('</nav>','</nav>'+dateline,1)
 nav=''.join(f'<a href="{base}{local(lang,s)}">{label}</a>' for s,label in zip(['products','about','sourcing-guide','contact'],t['nav']))
 body=enhance(lang,slug,body,base,ITEMS,LABEL_INDEX,local,cards)
 if slug=='index':body=refine_hero(lang,body,base,local,ITEMS,LABEL_INDEX)
 langs=''.join('<a href="'+base+local(code,slug if multilingual else 'index')+'" lang="'+code+'" hreflang="'+code+'" '+('aria-current="page"' if code==lang else '')+'>'+code.upper()+'</a>' for code in L)
 social_slug=slug.split('/')[-1]
 social_image='products/'+social_slug+'.webp' if social_slug in [it[0] for it in ITEMS] else IMAGES[GROUP_SLUGS.index(social_slug)] if social_slug in GROUP_SLUGS else IMAGES[0]
 html=f'''<!doctype html><html lang="{lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{esc(title)}</title><meta name="description" content="{esc(description,quote=True)}"><meta name="robots" content="{'noindex,follow' if noindex else 'index,follow,max-image-preview:large'}"><link rel="canonical" href="{canonical}">{alternates}<meta property="og:type" content="website"><meta property="og:title" content="{esc(title,quote=True)}"><meta property="og:description" content="{esc(description,quote=True)}"><meta property="og:url" content="{canonical}"><meta property="og:image" content="{DOMAIN}/img/{social_image}"><meta property="og:site_name" content="TVS Textile"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="{base}img/favicon.png"><link rel="stylesheet" href="{base}css/corporate.css"><script type="application/ld+json">{json.dumps(schema,ensure_ascii=False)}</script><script src="{base}js/corporate.js" defer></script></head><body><a class="skip-link" href="#main">{ {'en':'Skip to content','fr':'Aller au contenu','de':'Zum Inhalt','es':'Ir al contenido'}[lang]}</a><div class="topline"><span>DENİZLİ → YOUR WORLD</span><a href="mailto:ozkan@tvstextile.com">ozkan@tvstextile.com <span aria-hidden="true">↗</span></a></div><header class="site-header"><a class="brand" href="{base}{local(lang)}" aria-label="TVS Textile home"><img class="brand-logo" src="{base}img/tvslogo_yeni.webp" alt="TVS Tekstil" width="220" height="100"></a><button class="menu-toggle" aria-label="Menu" aria-controls="site-nav" aria-expanded="false">☰</button><nav id="site-nav" aria-label="Main navigation">{nav}<div class="languages" aria-label="{t['lang']}">{langs}</div></nav><a class="header-cta" href="{base}{local(lang,'contact')}">{t['cta']} <span aria-hidden="true">↗</span></a></header><main id="main">{body}</main><footer><div class="footer-lead"><a class="brand" href="{base}{local(lang)}"><img class="brand-logo" src="{base}img/tvslogo_yeni.webp" alt="TVS Tekstil" width="220" height="100"></a><h2>{t['footer']}</h2><a href="mailto:ozkan@tvstextile.com" class="footer-email">ozkan@tvstextile.com ↗</a></div><div class="footer-grid"><div><span class="eyebrow">DENİZLİ, TÜRKİYE</span><p>{ADDRESS}</p><a href="tel:+905324770375">+90 532 477 0375</a></div><div><span class="eyebrow">{t['nav'][0]}</span>{''.join(f'<a href="{base}{local(lang,"collections/"+s)}">{t["groups"][i]}</a>' for i,s in enumerate(GROUP_SLUGS))}</div><div><span class="eyebrow">TVS TEXTILE</span><a href="{base}{local(lang,'about')}">{t['about']}</a><a href="{base}{local(lang,'sourcing-guide')}">{t['guide']}</a><a href="{base}{local(lang,'contact')}">{t['contact']}</a><a href="{base}privacy.html">Privacy</a></div></div><div class="footer-bottom"><span>© 2026 TVS Textile</span><span>HOME · HOSPITALITY · BABY</span><a href="#main" aria-label="Back to top">↑</a></div></footer></body></html>'''
 locales=f'<meta property="og:locale" content="{COPY[lang]["locale"]}">'+''.join(f'<meta property="og:locale:alternate" content="{COPY[code]["locale"]}">' for code in L if code!=lang) if multilingual else ''
 html=html.replace('<meta property="og:type"',locales+'<meta property="og:type"',1)
 html=html.replace('</head>',f'<script src="{base}js/buyer-experience.js" defer></script></head>',1)
 write(file,html.replace('><','>\n<'))

def cta(lang,base):
 t=L[lang]; return f'<section class="project-section"><div class="project-orbit" aria-hidden="true"></div><span class="eyebrow">TVS TEXTILE / LET’S CONNECT</span><h2>{t["project"]}</h2><p>{t["project_sub"]}</p><a class="button light" href="{base}{local(lang,"contact")}">{t["cta"]} <span>↗</span></a></section>'

def build():
 for lang,t in L.items():
  base='' if lang=='en' else '../'
  body=f'''<section class="hero"><div class="hero-copy"><span class="eyebrow">{t['tag']}</span><h1>{t['hero']}</h1><p>{t['intro']}</p><a class="button" href="#collections">{t['explore']} <span>↗</span></a><div class="hero-foot"><span>HOME / HOSPITALITY / BABY</span><span>SCROLL TO DISCOVER ↓</span></div></div><div class="hero-visual">{image(0,base,True)}<div class="hero-stamp"><img src="{base}img/tvslogo_yeni.webp" alt="TVS Tekstil" width="220" height="100"></div><div class="photo-caption"><span>01 — THE HOME COLLECTION</span><span>Softness, in every detail.</span></div></div></section>{connection_band(lang)}<section class="section" id="collections"><div class="section-heading reveal"><div><span class="eyebrow">01 / {t['nav'][0]}</span><h2>{t['collection']}</h2></div><p>{t['collection_sub']}</p></div>{groups(lang,base)}</section>'''
  stories={'en':('Rooted in Denizli.<br><em>Connected to your world.</em>','TVS Textile brings home, hospitality and baby textiles to international buyers from Denizli, Türkiye. We start with your product brief: the purpose, the feel and the details that matter to your business.'),'fr':('Ancrés à Denizli.<br><em>Ouverts sur votre monde.</em>','TVS Textile propose du linge de maison, des textiles hôteliers et des articles bébé aux acheteurs internationaux depuis Denizli, en Türkiye. Votre cahier des charges est le point de départ de notre échange.'),'de':('In Denizli verwurzelt.<br><em>Mit Ihrer Welt verbunden.</em>','TVS Textile bietet Heimtextilien, Hoteltextilien und Babytextilien für internationale Einkäufer aus Denizli in Türkiye. Ihr Produktbrief ist der Ausgangspunkt unseres Gesprächs.'),'es':('Con raíces en Denizli.<br><em>Conectados con su mundo.</em>','TVS Textile ofrece textiles para el hogar, hostelería y bebé a compradores internacionales desde Denizli, Türkiye. Su ficha de producto es el punto de partida de nuestra conversación.')}
  st,sp=stories[lang]
  body+=f'<section class="story-section"><div class="story-image">{image(2,base)}<span class="story-label">A CONSIDERED APPROACH</span></div><div class="story-copy reveal"><span class="eyebrow">02 / TVS TEXTILE</span><h2>{st}</h2><p>{sp}</p><a class="text-link" href="{base}{local(lang,"about")}">{t["about"]} ↗</a><div class="story-values"><span>{t["groups"][0]}</span><span>{t["groups"][1]}</span><span>{t["groups"][2]}</span></div></div></section><section class="section"><div class="section-heading"><div><span class="eyebrow">03 / {t["buyer"]}</span><h2>{t["spec"]}</h2></div><p>{t["brief"]}</p></div><div class="brief-grid">'+''.join(f'<div class="brief-card reveal"><span>0{i+1}</span><h3>{h}</h3><p>{p}</p></div>' for i,(h,p) in enumerate({ 'en':[('Define the product','Choose a collection and share the materials, sizes and details you need.'),('Discuss the brief','Ask about samples, minimum quantities and the specifications for your project.'),('Plan the next step','Confirm the quote, agreed specifications and destination before placing your order.')], 'fr':[('Définir le produit','Choisissez une collection et précisez matières, dimensions et détails.'),('Échanger sur le projet','Discutez des échantillons, quantités minimales et spécifications.'),('Préparer la suite','Confirmez le devis, les spécifications et la destination avant la commande.')], 'de':[('Produkt definieren','Wählen Sie die Kollektion und nennen Sie Material, Maße und Details.'),('Brief besprechen','Fragen Sie nach Mustern, Mindestmengen und Spezifikationen.'),('Nächsten Schritt planen','Bestätigen Sie Angebot, Spezifikationen und Zielland vor der Bestellung.')], 'es':[('Definir el producto','Elija una colección e indique materiales, medidas y detalles.'),('Comentar el proyecto','Consulte muestras, cantidades mínimas y especificaciones.'),('Planificar el siguiente paso','Confirme presupuesto, especificaciones y destino antes del pedido.')]}[lang]))+'</div></section>'+cta(lang,base)
  page(lang,'index', {'en':'Turkish Home, Hotel & Baby Textiles | TVS Textile','fr':'Linge de maison, hôtel & bébé de Turquie | TVS Textile','de':'Heim-, Hotel- & Babytextilien aus der Türkei | TVS Textile','es':'Textiles de hogar, hotel y bebé de Turquía | TVS Textile'}[lang],t['intro'],body)
  page(lang,'products',t['nav'][0]+' | TVS Textile',t['collection_sub']+' '+', '.join(it[LABEL_INDEX[lang]] for it in ITEMS[:3]),f'<section class="page-intro"><span class="eyebrow">THE TVS COLLECTIONS</span><h1>{t["collection"]}</h1><p>{t["collection_sub"]}</p></section><section class="section">{groups(lang,base)}<div class="product-list">{cards(lang,base)}</div></section>'+cta(lang,base))
  for g,slug in enumerate(GROUP_SLUGS):
   groupbase='../' if lang=='en' else '../../'
   origin={'en':'from Türkiye','fr':'de Turquie','de':'aus der Türkei','es':'de Turquía'}[lang]
   page(lang,'collections/'+slug,t['groups'][g]+' '+origin+' | TVS Textile',t['groups'][g]+': '+', '.join(it[LABEL_INDEX[lang]] for it in ITEMS if it[1]==g)+'. '+t['brief'],f'<section class="split-intro"><div><a class="eyebrow" href="{groupbase}{local(lang,"products")}">← {t["back"]}</a><h1>{t["groups"][g]}</h1><p>{t["brief"]}</p><a class="button" href="{groupbase}{local(lang,"contact")}">{t["cta"]} ↗</a></div><div>{image(g,groupbase,True)}</div></section><section class="section"><div class="product-list">{cards(lang,groupbase,g)}</div><p class="image-note">{t["note"]}</p></section>'+cta(lang,groupbase))
  for item_index,it in enumerate(ITEMS):
   slug,g=it[:2]; name=it[LABEL_INDEX[lang]]; b='../' if lang=='en' else '../../'
   detail=it[7] if lang=='en' else DETAILS[lang][item_index]
   summary=it[6] if lang=='en' else t['buyer']+' · '+t['groups'][g]
   body=f'<section class="split-intro"><div><a class="eyebrow" href="{b}{local(lang,"collections/"+GROUP_SLUGS[g])}">← {t["groups"][g]}</a><h1>{name}</h1><p>{summary}</p><a class="button" href="{b}{local(lang,"contact")}?product={slug}">{t["inquiry"]} ↗</a></div><div>{product_image(slug,lang,b,True)}</div></section><section class="section product-detail"><div><span class="eyebrow">{t["buyer"]}</span><h2>{t["spec"]}</h2><p>{detail}</p><p>{t["brief"]}</p></div><aside><h3>{t["inquiry"]}</h3><p>{name} / {t["groups"][g]}</p><a class="text-link" href="mailto:ozkan@tvstextile.com?subject={slug}">ozkan@tvstextile.com ↗</a><p class="image-note">{t["note"]}</p></aside></section><section class="section"><h2>{t["related"]}</h2><div class="product-list">{cards(lang,b,g,exclude=slug)}</div></section>'+cta(lang,b)
   suffix={'en':'Turkish Textile Manufacturer','fr':'Fabricant textile en Turquie','de':'Textilhersteller in der Türkei','es':'Fabricante textil en Turquía'}[lang]
   desc={'en':'Textile sourcing from Denizli, Türkiye. Discuss materials, dimensions, samples and order quantities with TVS Textile.','fr':'Textiles de Denizli, Turquie. Discutez des matières, dimensions, échantillons et quantités avec TVS Textile.','de':'Textilien aus Denizli, Türkei. Besprechen Sie Material, Maße, Muster und Bestellmengen mit TVS Textile.','es':'Textiles de Denizli, Turquía. Consulte materiales, medidas, muestras y cantidades con TVS Textile.'}[lang]
   page(lang,'collections/'+slug,name+' | '+suffix+' | TVS Textile',name+'. '+desc,body)
  page(lang,'about',t['about']+' | TVS Textile, Denizli',sp,f'<section class="page-intro"><span class="eyebrow">DENİZLİ, TÜRKİYE / TVS TEXTILE</span><h1>{st}</h1><p>{sp}</p></section><section class="section">{groups(lang,base)}</section><section class="section product-detail"><div><h2>{t["spec"]}</h2><p>{t["brief"]}</p></div><aside><h3>{t["contact"]}</h3><p>{ADDRESS}</p><a href="tel:+905324770375">+90 532 477 0375</a><p><a href="mailto:ozkan@tvstextile.com">ozkan@tvstextile.com</a></p></aside></section>'+cta(lang,base))
  build_contact(lang,base)
  build_guide(lang,base)
 build_legacy()
 paths=[p for p in ROOT.glob('*.html') if p.stem not in ['404','post','product-detail']]+list((ROOT/'collections').glob('*.html'))
 for lang in ['fr','de','es']: paths+=list((ROOT/lang).rglob('*.html'))
 write_sitemap(ROOT,paths)
 write('robots.txt','User-agent: *\nAllow: /\nDisallow: /admin/\nDisallow: /admin-panel/\nDisallow: /.private/\nDisallow: /tools/\nDisallow: /TVSTÜRKÇE/\nDisallow: /.git/\n\nSitemap: '+DOMAIN+'/sitemap.xml\n')

def build_contact(lang,base):
 t=L[lang]
 labels={'en':['Your name','Company','Email','Destination country','Product / collection','Estimated quantity','Your project brief','Prepare email enquiry','This form prepares an email in your email app. Review it and press Send there. Your enquiry is not sent by this website.'], 'fr':['Votre nom','Entreprise','E-mail','Pays de destination','Produit / collection','Quantité estimée','Votre projet','Préparer un e-mail','Ce formulaire prépare un e-mail dans votre messagerie. Vérifiez-le puis envoyez-le. Le site ne transmet pas votre demande.'], 'de':['Ihr Name','Unternehmen','E-Mail','Zielland','Produkt / Kollektion','Geschätzte Menge','Ihr Projekt','E-Mail-Anfrage vorbereiten','Dieses Formular öffnet eine E-Mail in Ihrem E-Mail-Programm. Prüfen und senden Sie sie dort. Die Website sendet Ihre Anfrage nicht.'], 'es':['Su nombre','Empresa','Correo electrónico','País de destino','Producto / colección','Cantidad estimada','Su proyecto','Preparar consulta por correo','Este formulario prepara un correo en su aplicación. Revíselo y envíelo allí. El sitio no envía su consulta.']}[lang]
 fields=''
 for i,key in enumerate(['name','subject','email','country','product','quantity']):
  if key=='product': control=f'<select id="{key}" name="{key}"><option value="">—</option>'+''.join(f'<option value="{it[0]}">{it[LABEL_INDEX[lang]]}</option>' for it in ITEMS)+'</select>'
  else: control=f'<input id="{key}" name="{key}" type="{"email" if key=="email" else "text"}" {"required" if key in ["name","email","country"] else ""} autocomplete="{ {"name":"name","subject":"organization","email":"email","country":"country-name"}.get(key,"off")}" maxlength="200">'
  fields+=f'<label for="{key}">{labels[i]}{control}</label>'
 send={'en':'Send enquiry','fr':'Envoyer la demande','de':'Anfrage senden','es':'Enviar consulta'}[lang]
 phone={'en':'Phone (optional)','fr':'Téléphone (facultatif)','de':'Telefon (optional)','es':'Teléfono (opcional)'}[lang]
 body=f'<section class="page-intro"><span class="eyebrow">LET’S CONNECT / TVS TEXTILE</span><h1>{t["project"]}</h1><p>{t["project_sub"]}</p></section><section class="section contact-layout"><div class="contact-details"><h2>{t["contact"]}</h2><a class="contact-email" href="mailto:ozkan@tvstextile.com">ozkan@tvstextile.com ↗</a><a href="tel:+905324770375">+90 532 477 0375</a><p>{ADDRESS}</p><a class="text-link" href="https://www.google.com/maps/search/?api=1&amp;query=Ak%C3%A7e%C5%9Fme+2605+Sk+40+Merkezefendi+Denizli" target="_blank" rel="noopener">Google Maps ↗</a><p>{t["brief"]}</p></div><form id="enquiry-form" action="/admin/api/quotes" method="post"><div class="form-grid">{fields}</div><label for="phone">{phone}<input id="phone" name="phone" type="tel" autocomplete="tel" maxlength="100"></label><label for="message">{labels[6]}<textarea id="message" name="message" rows="5" required maxlength="4000"></textarea></label><button class="button" type="submit">{send} ↗</button><p id="form-status" role="status" aria-live="polite"></p><noscript><p>Please email ozkan@tvstextile.com directly; JavaScript is needed to send this form.</p></noscript></form></section>'
 page(lang,'contact',t['contact']+' | Textile Enquiries | TVS Textile',t['project_sub'],body)

def build_guide(lang,base):
 t=L[lang]
 texts={'en': [('Start with the intended use','A home bedding collection, a hotel replenishment order and a baby range have different requirements. Explain the intended customer and use before choosing the textile specification.'),('Specify the details that affect the quote','Include dimensions, composition, fabric weight where relevant, colours, quantities per variant, finishing and packaging preferences. Share your destination and target schedule.'),('Request samples and supporting documents','Ask which samples and product documents are available for your brief. Confirm any required certification, laboratory testing or destination-market compliance against the actual product. No certification should be assumed from a category photograph.'),('Agree commercial and delivery terms','Confirm minimum quantities, sample approval, lead time, payment terms, shipping responsibility and the agreed delivery term in writing. These depend on the project and need a specific quotation.')], 'fr':[('Définir l’usage','Une collection pour la maison, un hôtel ou un bébé nécessite des spécifications différentes. Précisez le client et l’usage prévu.'),('Préciser les détails','Indiquez dimensions, composition, grammage, couleurs et quantités par variante. Ajoutez destination, emballage et calendrier souhaité.'),('Demander les documents','Vérifiez la disponibilité des échantillons et documents. Les certifications et essais doivent être confirmés pour le produit final et le marché visé.'),('Confirmer les conditions','Convenez par écrit des quantités minimales, échantillons, délais, paiement et responsabilités de transport. Ces conditions dépendent du projet.')], 'de':[('Verwendung festlegen','Heimtextilien, Hotelbedarf und Babyprodukte benötigen unterschiedliche Spezifikationen. Beschreiben Sie Kunden und Verwendungszweck.'),('Details angeben','Nennen Sie Maße, Zusammensetzung, Stoffgewicht, Farben und Mengen je Variante sowie Zielland, Verpackung und Zeitplan.'),('Dokumente anfordern','Fragen Sie nach Mustern und Produktunterlagen. Zertifikate und Prüfungen müssen für das tatsächliche Produkt und den Zielmarkt bestätigt werden.'),('Bedingungen bestätigen','Vereinbaren Sie Mindestmengen, Musterfreigabe, Lieferzeit, Zahlung und Transportverantwortung schriftlich. Diese Bedingungen sind projektabhängig.')], 'es':[('Definir el uso','Hogar, hotel y bebé necesitan especificaciones diferentes. Describa el cliente y el uso previsto.'),('Indicar los detalles','Incluya medidas, composición, gramaje, colores y cantidades por variante, además del destino, embalaje y calendario.'),('Solicitar documentación','Consulte muestras y documentos disponibles. Certificaciones y ensayos deben verificarse para el producto final y el mercado de destino.'),('Confirmar las condiciones','Acuerde por escrito cantidades mínimas, muestras, plazos, pago y responsabilidades de transporte. Estas condiciones dependen del proyecto.')]}[lang]
 body=f'<section class="page-intro"><span class="eyebrow">FOR INTERNATIONAL BUYERS</span><h1>{t["guide"]}</h1><p>{t["brief"]}</p></section><section class="section guide-list">'+''.join(f'<article class="guide-row reveal"><span>0{i+1}</span><div><h2>{h}</h2><p>{p}</p></div></article>' for i,(h,p) in enumerate(texts))+'</section>'+cta(lang,base)
 page(lang,'sourcing-guide',t['guide']+' | Buying Textiles from Türkiye | TVS Textile',t['brief'],body)

def build_legacy():
 page('en','blog','Textile Sourcing Resources | TVS Textile','A practical guide to planning textile enquiries, samples and specifications.', '<section class="page-intro"><span class="eyebrow">THE BUYER’S EDIT</span><h1>Better briefs.<br><em>Better conversations.</em></h1><p>Practical considerations for sourcing home, hospitality and baby textiles.</p><a class="button" href="sourcing-guide.html">Read the sourcing guide ↗</a></section>',True)
 page('en','post','Textile Resources | TVS Textile','Explore textile sourcing resources.','<section class="page-intro"><h1>Explore our sourcing guide.</h1><a class="button" href="sourcing-guide.html">Read the guide ↗</a></section>',True)
 page('en','product-detail','Bed Linen Set | TVS Textile','Discuss your bed linen set requirements with TVS Textile.','<section class="page-intro"><span class="eyebrow">HOME TEXTILES</span><h1>Bed linen set</h1><p>The previously listed double-size bed linen set is now part of our enquiry-based collection. Confirm current availability, composition and dimensions with our team.</p><a class="button" href="collections/duvet-covers.html">Explore duvet covers ↗</a><p><a href="contact.html?product=duvet-covers">Enquire about a bed linen set ↗</a></p></section>',True)
 page('en','404','Page Not Found | TVS Textile','Find TVS Textile collections and contact information.','<section class="page-intro"><span class="eyebrow">404 / A LOOSE THREAD</span><h1>Let’s find<br><em>your way back.</em></h1><a class="button" href="index.html">Back to home ↗</a></section>',True)
 page('en','privacy','Contact Data | TVS Textile','Information about contact enquiries on the TVS Textile website.','<section class="page-intro"><h1>Contact data</h1><p>When you submit a project enquiry, the details you enter are sent to the website’s existing enquiry service so TVS Textile can respond. Please include business and project information relevant to your request.</p><p>Your product selection, quantities and collection notes are saved in your browser so you can continue building your collection across pages and languages. They are not sent to TVS Textile until you submit the enquiry form. Removing products and clearing your notes updates this browser storage. The website does not add analytics cookies. The hosting provider processes requests to deliver the website. Google Maps is an external link and applies its own policies when opened.</p><p>For questions about information you share or requests concerning your enquiry, contact ozkan@tvstextile.com.</p></section>')
 mapping={'banyo':'hotel-spa-textiles','yatak-takimi':'home-textiles','ev-kiyafeti':'home-textiles','bebek-cocuk':'baby-textiles','yasam':'home-textiles','beach-spa':'hotel-spa-textiles'}
 for old,new in mapping.items():
  write('kategori/'+old+'.html',f'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="robots" content="noindex,follow"><meta http-equiv="refresh" content="0;url=../collections/{new}.html"><link rel="canonical" href="{DOMAIN}/collections/{new}.html"><title>Collection moved | TVS Textile</title></head><body><a href="../collections/{new}.html">Explore the collection</a></body></html>')

if __name__=='__main__': build()
