import json, re
from html import escape

COPY={
 'en':dict(title='Your business. Your textile edit.',intro='Start with the way you buy. We will bring the relevant collections into focus.',tabs=['All collections','My brand / retail','Hotel & spa','Baby collection'],leads=['Explore all twelve products and build your own shortlist.','Shape a bedding range for your own label or retail collection.','Bring guest rooms, bathrooms and treatment spaces into one brief.','Explore a baby range, then discuss age, materials and final specifications.'],save='Add to my collection',saved='In my collection',collection='My collection',empty='Your next collection starts here. Add products as you explore.',remove='Remove',quantity='Quantity',notes='Collection notes',enquire='Discuss this collection',download='Download collection file',print='Print / save PDF',close='Close',texture='Explore the texture',zoom='Detail zoom',concept='Generated concept image. Ask us for real product close-ups and samples.',date='Prepared',file='TVS Textile — collection brief',status='Collection updated',back='Browse collections'),
 'fr':dict(title='Votre activité. Votre sélection textile.',intro='Commencez par votre projet : les collections pertinentes passent au premier plan.',tabs=['Toutes les collections','Ma marque / boutique','Hôtel & spa','Collection bébé'],leads=['Découvrez douze produits et composez votre sélection.','Préparez une gamme de linge de lit pour votre marque ou boutique.','Réunissez chambre, salle de bain et soins dans un même projet.','Explorez une gamme bébé, puis échangeons sur les âges, matières et spécifications.'],save='Ajouter à ma sélection',saved='Dans ma sélection',collection='Ma sélection',empty='Votre collection commence ici. Ajoutez des produits au fil de votre visite.',remove='Retirer',quantity='Quantité',notes='Notes du projet',enquire='Discuter de cette sélection',download='Télécharger la sélection',print='Imprimer / enregistrer en PDF',close='Fermer',texture='Explorer la texture',zoom='Zoom sur les détails',concept='Image conceptuelle générée. Demandez des gros plans réels et des échantillons.',date='Préparé le',file='TVS Textile — sélection de produits',status='Sélection mise à jour',back='Parcourir les collections'),
 'de':dict(title='Ihr Geschäft. Ihre Textilauswahl.',intro='Beginnen Sie mit Ihrem Vorhaben. Die passenden Kollektionen rücken in den Mittelpunkt.',tabs=['Alle Kollektionen','Meine Marke / Handel','Hotel & Spa','Babykollektion'],leads=['Entdecken Sie zwölf Produkte und stellen Sie Ihre Auswahl zusammen.','Planen Sie Bettwäsche für Ihre Marke oder Ihr Einzelhandelssortiment.','Verbinden Sie Gästezimmer, Bad und Spa in einer Anfrage.','Entdecken Sie Babytextilien und besprechen Sie Alter, Material und Spezifikationen.'],save='Zur Auswahl hinzufügen',saved='In meiner Auswahl',collection='Meine Auswahl',empty='Ihre Kollektion beginnt hier. Fügen Sie beim Entdecken Produkte hinzu.',remove='Entfernen',quantity='Menge',notes='Projektnotizen',enquire='Diese Auswahl besprechen',download='Auswahl herunterladen',print='Drucken / als PDF speichern',close='Schließen',texture='Textur entdecken',zoom='Detailvergrößerung',concept='Generiertes Konzeptbild. Fragen Sie nach echten Nahaufnahmen und Mustern.',date='Erstellt am',file='TVS Textile — Produktauswahl',status='Auswahl aktualisiert',back='Kollektionen entdecken'),
 'es':dict(title='Su negocio. Su selección textil.',intro='Empiece por su proyecto. Destacaremos las colecciones que encajan con él.',tabs=['Todas las colecciones','Mi marca / tienda','Hotel & spa','Colección de bebé'],leads=['Explore doce productos y prepare su selección.','Diseñe una gama de ropa de cama para su marca o tienda.','Reúna habitaciones, baños y espacios de spa en una consulta.','Explore textiles de bebé y consulte edades, materiales y especificaciones.'],save='Añadir a mi selección',saved='En mi selección',collection='Mi selección',empty='Su colección empieza aquí. Añada productos mientras explora.',remove='Eliminar',quantity='Cantidad',notes='Notas del proyecto',enquire='Consultar esta selección',download='Descargar la selección',print='Imprimir / guardar PDF',close='Cerrar',texture='Explorar la textura',zoom='Ampliar los detalles',concept='Imagen conceptual generada. Solicite primeros planos reales y muestras.',date='Preparado el',file='TVS Textile — selección de productos',status='Selección actualizada',back='Explorar las colecciones')}

def enhance(lang,slug,body,base,items,index,local,cards):
 c=COPY[lang]
 def button(s):return f'<button class="save-product" type="button" data-save="{s}" aria-pressed="false">＋ {c["save"]}</button>'
 pattern=r'<a class="product-tile reveal" href="([^"]+)">(.*?)</a>'
 def tile(m):
  s=m[1].split('/')[-1].replace('.html','')
  return f'<article class="product-entry" data-group="{next(it[1] for it in items if it[0]==s)}"><a class="product-tile reveal" href="{m[1]}">{m[2]}</a>{button(s)}</article>'
 body=re.sub(pattern,tile,body,flags=re.S)
 if slug=='index':
  showcase=f'<section class="section buyer-showcase" aria-labelledby="buyer-title"><div class="section-heading"><div><span class="eyebrow">TVS / YOUR COLLECTION EDIT</span><h2 id="buyer-title">{c["title"]}</h2></div><p>{c["intro"]}</p></div><div class="buyer-tabs" role="group" aria-label="{c["title"]}">'+''.join(f'<button type="button" data-buyer="{g}" aria-pressed="{"true" if i==0 else "false"}">{name}</button>' for i,(g,name) in enumerate(zip(['all','0','1','2'],c['tabs'])))+f'</div><p class="buyer-lead" aria-live="polite">{c["leads"][0]}</p><div class="product-list buyer-products">{cards(lang,base)}</div></section>'
  showcase=re.sub(pattern,tile,showcase,flags=re.S)
  body=body.replace('<section class="story-section">',showcase+'<section class="story-section">',1)
 tail=slug.split('/')[-1]
 if slug.startswith('collections/') and tail in [it[0] for it in items]:
  body=body.replace('</div><div><img',f'<div class="product-tools">{button(tail)}<button type="button" class="texture-open" data-texture="{tail}">⌕ {c["texture"]}</button></div></div><div><img',1)
 catalog=[dict(slug=it[0],name=it[index[lang]],group=it[1],url=base+local(lang,'collections/'+it[0]),image=base+'img/products/'+it[0]+'.webp') for it in items]
 data=json.dumps(dict(copy=c,products=catalog,contact=base+local(lang,'contact'),productsUrl=base+local(lang,'products'),logo=base+'img/tvslogo_yeni.webp'),ensure_ascii=False).replace('<','\\u003c')
 body+=f'''<script type="application/json" id="buyer-data">{data}</script><button type="button" class="collection-launch" aria-haspopup="dialog">{c['collection']} <span class="collection-count">0</span></button><span id="collection-status" class="sr-only" role="status"></span>
 <dialog id="collection-dialog" class="collection-dialog" aria-labelledby="collection-title"><div class="collection-dialog-head"><div><span class="eyebrow">TVS TEXTILE / COLLECTION EDIT</span><h2 id="collection-title">{c['collection']}</h2></div><button class="dialog-close" type="button" aria-label="{c['close']}">×</button></div><div id="collection-items"></div><label class="collection-notes">{c['notes']}<textarea id="collection-notes" rows="3" maxlength="2000"></textarea></label><div class="collection-actions"><button type="button" class="button" id="collection-enquire">{c['enquire']} ↗</button><button type="button" id="collection-download">{c['download']} ↓</button><button type="button" id="collection-print">{c['print']}</button></div><p class="collection-disclaimer">{c['concept']}</p></dialog>
 <dialog id="texture-dialog" class="texture-dialog" aria-labelledby="texture-title"><div class="collection-dialog-head"><div><span class="eyebrow">TVS / TEXTURE STUDY</span><h2 id="texture-title">{c['texture']}</h2></div><button class="dialog-close" type="button" aria-label="{c['close']}">×</button></div><div class="texture-stage"><img id="texture-image" alt="" width="1536" height="1024"></div><label class="texture-control">{c['zoom']}<input id="texture-zoom" type="range" min="1" max="3" step="0.1" value="1"><output id="texture-value">1×</output></label><p>{c['concept']}</p></dialog>'''
 return body
