const fs=require('fs'),vm=require('vm'),assert=require('assert');
const html=fs.readFileSync('index.html','utf8');
const data=JSON.parse(html.match(/<script type="application\/json" id="buyer-data">([\s\S]*?)<\/script>/)[1]);
class Node{constructor(){this.events={};this.children=[];this.style={};this.value='';this.dataset={};}addEventListener(type,fn){this.events[type]=fn;}append(...n){this.children.push(...n);}replaceChildren(){this.children=[];}setAttribute(k,v){this[k]=v;}querySelector(){return new Node();}click(){if(this.tag==='a')download=this;else this.events.click?.({});}remove(){}showModal(){this.open=true;}close(){this.open=false;}getBoundingClientRect(){return{left:0,top:0,width:300,height:200};}}
let download,blob,navigation,stored;
const nodes=new Map();const get=s=>{if(!nodes.has(s))nodes.set(s,new Node());return nodes.get(s);};
get('#buyer-data').textContent=JSON.stringify(data);
const state={items:[{slug:'towels',quantity:'500'},{slug:'bad-slug',quantity:'1'}],notes:'<script>alert(1)</script> & buyer notes'};
const document={documentElement:{lang:'en'},body:new Node(),querySelector:s=>s==='#enquiry-form'?null:get(s),querySelectorAll:()=>[],createElement:tag=>{const n=new Node();n.tag=tag;return n;}};
class TestURL extends URL{static createObjectURL(b){blob=b;return'blob:test';}static revokeObjectURL(){}}
const context={document,localStorage:{getItem:()=>JSON.stringify(state),setItem:(k,v)=>stored=v},sessionStorage:{setItem:(k,v)=>stored=v,getItem:()=>stored},location:{search:'',href:'https://www.tvstextile.com/',assign:v=>navigation=v},URL:TestURL,URLSearchParams,Blob,fetch:async()=>{throw Error('offline logo');},setTimeout:()=>{},window:{print:()=>{}},FileReader:class{}};
vm.runInNewContext(fs.readFileSync('js/buyer-experience.js','utf8'),context);
(async()=>{await get('#collection-download').events.click();assert(download.download.endsWith('.html'));const exported=await blob.text();assert(exported.includes('Towels — Quantity: 500'));assert(exported.includes('&lt;script&gt;'));assert(!exported.includes('<script>alert'));assert(!exported.includes('bad-slug'));context.fetch=async url=>({ok:true,blob:async()=>new Blob([fs.readFileSync(url)])});context.FileReader=class{readAsDataURL(){this.result='data:image/webp;base64,verified';this.onload();}};await get('#collection-download').events.click();const illustrated=await blob.text();assert(illustrated.includes('class="product" src="data:image/webp;base64,verified'));assert(illustrated.includes('alt="TVS Tekstil"'));get('#collection-enquire').events.click();assert(stored.includes('Towels — Quantity: 500'));assert(navigation==='https://www.tvstextile.com/contact.html?collection=1');assert(!navigation.includes('buyer'));console.log('PASS: invalid stored products rejected; standalone export embeds logo/product images, escapes notes and includes quantities; enquiry transfer keeps the brief out of URLs.');})().catch(e=>{console.error(e);process.exit(1);});
