"""Original company-voice copy. Dates record edits, not invented trading history."""
UPDATED='2026-10-04'
FOUNDED='2021'
DATES={'en':'Content updated: 4 October 2026','fr':'Contenu mis à jour : 4 octobre 2026','de':'Inhalt aktualisiert: 4. Oktober 2026','es':'Contenido actualizado: 4 de octubre de 2026'}
PRODUCTS={
 'en':[
  ('We see muslin bedding as a choice of texture, not just a name on a fabric list.', 'The feel we want to define together', 'When you describe a muslin duvet cover to us, we want to understand how it should feel on the bed. A light, airy appearance and a more substantial layered fabric lead to different briefs. We therefore start the conversation with composition, the number of gauze layers and your preferred finished dimensions.', 'We also want to discuss what happens after washing. The agreed dimensions should make sense alongside the expected shrinkage and care instructions. If this cover belongs to a larger bedding range, send us the pillowcase sizes and colour references too; we can then discuss the collection as a whole.'),
  ('For us, a fitted sheet begins with the mattress it needs to fit.', 'We look beyond width and length', 'A mattress measurement without its depth leaves an important part of a fitted-sheet brief unanswered. We ask you to describe all three dimensions, whether a topper is used and how you want the elastic to sit. That gives our discussion a practical starting point rather than relying on labels such as double or king.', 'Your intended market also matters to the size brief. We want to agree the actual measurements and composition, then discuss laundering and the expected fit after washing. For a coordinated range, tell us which duvet covers the sheet will accompany and whether each colour needs its own quantity breakdown.'),
  ('We think of a duvet cover as the centre of a coordinated bedding collection.', 'The closure is part of the design', 'Colour and fabric set the direction, but we do not want the small details to be lost in the enquiry. The duvet dimensions, opening position and preferred fastening belong in the same brief. We ask you to share whether the cover is intended for a home collection or hospitality use, because the practical priorities can differ.', 'We prefer to discuss the pillowcases at the same time. Their dimensions, edging and quantities help us understand what a complete set should contain. A design reference is useful, but the written specification should still describe the agreed composition, colour and finishing so the quotation has a clear basis.'),
  ('We approach a bathrobe as something a guest or customer will wear, not simply a textile measured by weight.', 'We begin with the wearer and the setting', 'A spa robe and a homewear robe can share a fabric yet need different shapes. We ask about the intended wearer, the size range and your preferred collar, hood and belt details. Fabric weight is part of that conversation, alongside the feel and drying expectations you want us to consider.', 'For hotel projects, we also want to know how the robes will be laundered and identified. If you need embroidery, describe its position and send a suitable artwork reference. We discuss those details before treating the robe as a finished specification; quantities should be broken down by size rather than supplied as one total.'),
  ('For us, a towel brief should explain what the towel is expected to do.', 'We balance size, weight and intended use', 'A hand towel, a bath towel and a spa towel should not be reduced to one generic specification. We ask for the dimensions and quantities of each format, then discuss composition, weight in GSM and colour. Those details let us understand the range you are trying to build.', 'We also ask about care conditions because hotel laundering and domestic washing can set different priorities. A heavier towel is not automatically the right choice for every project. Tell us how you want to balance feel, absorbency requirements and drying expectations, and which border or identification details belong in the brief.'),
  ('We see a sauna wrap as a product whose fit deserves as much attention as its fabric.', 'We work from coverage and fastening', 'Before discussing a sauna wrap, we want to know the coverage you have in mind. Length, waist range and fastening preferences determine how the product should be specified. We ask you to describe the intended spa or sauna setting rather than assume that one size will suit every guest.', 'Fabric weight and absorbency requirements come next, together with laundering conditions. We also want to clarify whether you need one unisex format or separate variants. Breaking the enquiry down this way gives the quotation a clearer basis and helps avoid an attractive photograph standing in for the actual measurements.'),
  ('We treat a spa headband as a functional part of a treatment routine.', 'We ask how it will be worn', 'The width of the band and the head circumference range tell us more than a colour reference alone. We want to discuss whether you prefer an elastic fit or an adjustable fastening, and how the band should keep hair away from the treatment area. Describe the setting and the intended wearer in your enquiry.', 'For a spa collection, we also consider how you want the band to coordinate with the towels and wraps. Share the care conditions and quantity per colour, and tell us about any identification detail. We keep those requirements separate from decorative preferences so that the brief remains easy to review.'),
  ('We discuss makeup remover cloths through their surface, size and intended routine.', 'We keep the textile brief specific', 'A small cloth can have a very different purpose from a bath towel. We ask what dimensions you need and which composition and surface texture you want us to consider. The intended use should be stated clearly; we do not infer skin benefits or cleansing performance from a photograph.', 'Packaging and care information also belong in the conversation. Tell us the number of cloths per pack, your preferred colour breakdown and how you expect the textile to be washed. If the cloth is part of a wider spa range, we can discuss the visual coordination without assuming that every item needs the same fabric.'),
  ('We begin a baby poncho enquiry with the child’s size and the way the poncho will be used.', 'We define the shape before the colour', 'The intended age range is useful, but we also want the finished dimensions rather than relying on age labels alone. We ask you to describe the hood, the opening and the coverage you have in mind. The fabric and care instructions then become part of a more complete brief.', 'A bath collection and a beach collection can ask different things of a poncho. Tell us which setting you are planning and how the product should coordinate with the rest of your range. Any destination-market labelling or testing requirement needs to be discussed for the actual design; we do not assume that a category image proves compliance.'),
  ('We see a baby swaddle brief as a conversation about fabric, dimensions and the product’s intended use.', 'We ask you to describe the purpose clearly', 'The word swaddle can cover different textile formats. We therefore want to agree what the product is intended to be, along with the finished dimensions and composition. Colour and print references are helpful once that foundation is clear. If several sizes are planned, list them separately with their quantities.', 'We also want to discuss the instructions and labelling required for your market. We do not make sleep-safety claims from a fabric description. The final use, care information and any applicable requirements need to be considered alongside the actual product specification before an order is agreed.'),
  ('We do not treat a baby sleeping bag as an ordinary bedding accessory.', 'We put the final specification first', 'When you enquire about a baby sleeping bag, we ask for the intended age and size range, the season of use and your preferred fastening arrangement. We want to understand the construction you are considering rather than choose a thermal rating from a product photograph.', 'Thermal performance, fit, labelling and applicable safety testing need to be verified for the final design and destination market. We do not publish an assumed TOG value or certification. Your enquiry should identify the requirements you need to meet so that the conversation can focus on documented specifications and the next steps for that product.'),
  ('We approach a baby comforter through its textile details and the final design.', 'We ask about more than appearance', 'For a comforter or doudou, we want to understand the dimensions, fabric and any attached features. A reference image can show the visual direction, but it does not replace a description of seams, attachments or the intended age. We ask you to bring those details into the enquiry from the outset.', 'The destination market and labelling requirements are also relevant. Any applicable safety assessment should concern the actual finished design, not a general category name. We can discuss colour and collection coordination while keeping those product requirements visible; the quantities should distinguish each variant you intend to order.')
 ],
 'fr':[
  ('Pour nous, une housse de couette en gaze de coton se choisit d’abord pour sa texture.', 'Nous commençons par le toucher recherché', 'Lorsque vous nous présentez une collection en gaze de coton, nous cherchons à comprendre le rendu souhaité sur le lit. Une étoffe légère et un tissu composé de plusieurs couches ne donnent pas le même point de départ. Nous vous proposons donc de préciser la composition, le nombre de couches et les dimensions finies.', 'Nous souhaitons aussi parler du lavage avant de figer le cahier des charges. Le retrait attendu et les instructions d’entretien doivent être cohérents avec les mesures convenues. Pour un ensemble coordonné, transmettez-nous également les dimensions des taies et vos références de couleur : nous pourrons aborder toute la gamme dans le même échange.'),
  ('Nous partons du matelas pour parler d’un drap-housse, pas seulement du nom de sa taille.', 'La hauteur du matelas fait partie du projet', 'La largeur et la longueur ne suffisent pas à décrire l’ajustement recherché. Nous vous demandons également la hauteur du matelas, la présence éventuelle d’un surmatelas et vos préférences pour les élastiques. Ces informations rendent la discussion plus précise qu’une simple mention de lit double.', 'Nous souhaitons convenir des mesures réelles et de la composition, puis aborder le comportement attendu après lavage. Si le drap-housse accompagne une housse de couette, précisez les couleurs à coordonner. Les quantités par taille et par couleur nous donnent une lecture plus claire de votre collection.'),
  ('Nous considérons la housse de couette comme une pièce centrale de votre linge de lit.', 'Nous donnons une place aux détails de fermeture', 'Le tissu et la couleur orientent la collection, mais nous souhaitons aussi préciser les dimensions, la position de l’ouverture et le type de fermeture. Présentez-nous l’usage prévu : une gamme pour la maison et un projet hôtelier peuvent avoir des priorités pratiques différentes.', 'Nous préférons aborder les taies dans le même échange. Leurs mesures, leurs finitions et leur nombre permettent de définir ce que votre ensemble doit contenir. Une image de référence est utile ; nous voulons néanmoins un descriptif écrit des matières, couleurs et finitions pour que la demande de devis repose sur des éléments explicites.'),
  ('Pour nous, un peignoir se définit autour de la personne qui le portera et de son usage.', 'Nous parlons de la coupe avant de résumer le tissu', 'Un peignoir pour le spa et un modèle pour la maison peuvent demander des silhouettes différentes. Nous vous invitons à préciser les tailles, le col ou la capuche, la ceinture et le toucher recherché. Le grammage fait partie de l’échange, sans remplacer ces détails de coupe.', 'Pour l’hôtellerie, nous souhaitons connaître les conditions de lavage et les besoins d’identification. Si vous prévoyez une broderie, indiquez son emplacement et partagez une référence graphique adaptée. Nous vous proposons de répartir les quantités par taille afin de discuter du projet avec davantage de précision.'),
  ('Nous voulons savoir ce que vous attendez d’une serviette avant de parler de grammage.', 'Nous distinguons les formats et les usages', 'Une serviette pour les mains, une serviette de bain et une serviette de spa ne se décrivent pas nécessairement de la même façon. Nous vous demandons les dimensions et les quantités de chaque format, puis les matières et les couleurs envisagées. Cela nous aide à comprendre la gamme que vous souhaitez construire.', 'Nous souhaitons également aborder l’entretien. Les conditions de lavage d’un hôtel peuvent orienter le projet différemment d’un usage domestique. Un grammage élevé n’est pas une réponse universelle : présentez-nous vos attentes de toucher, d’absorption et de séchage, ainsi que les bordures ou détails d’identification à prévoir.'),
  ('Nous abordons le kilt de sauna par son ajustement et la couverture souhaitée.', 'Nous précisons la longueur et la fermeture', 'Avant de discuter du tissu, nous souhaitons connaître la longueur, le tour de taille et le système de fermeture envisagés. Présentez-nous le cadre d’utilisation du sauna ou du spa. Nous préférons définir les mesures utiles plutôt que supposer qu’une taille unique répondra à tous les besoins.', 'Le grammage, les attentes d’absorption et les conditions de lavage complètent ensuite le cahier des charges. Dites-nous si vous recherchez un modèle unisexe ou plusieurs variantes. Cette distinction permet de relier chaque quantité à un format précis, au lieu de laisser une photographie tenir lieu de spécification.'),
  ('Nous voyons le bandeau de spa comme un accessoire lié au déroulement du soin.', 'Nous demandons comment le bandeau sera porté', 'La largeur, le tour de tête et le type de maintien donnent une base concrète à notre discussion. Souhaitez-vous un ajustement élastique ou une fermeture réglable ? Présentez-nous le soin et l’utilisateur prévus pour que nous puissions parler de la fonction du bandeau avant de nous concentrer sur sa couleur.', 'Pour une collection de spa, nous pouvons aussi discuter de l’accord visuel avec vos serviettes et kilts. Précisez les conditions de lavage, les quantités par couleur et les détails d’identification. Nous gardons ces éléments fonctionnels dans le cahier des charges afin que les choix décoratifs ne les masquent pas.'),
  ('Nous parlons d’une lingette démaquillante à partir de sa surface, de son format et de l’usage prévu.', 'Nous décrivons le textile sans présumer ses effets', 'Une petite lingette ne se définit pas comme une serviette de bain. Nous vous invitons à préciser les dimensions, la composition et la texture recherchées. Nous ne déduisons pas de bénéfice pour la peau ni de performance de nettoyage à partir d’une photo : l’usage doit être décrit dans votre demande.', 'Le conditionnement et l’entretien font également partie de l’échange. Indiquez le nombre de lingettes par lot, les couleurs et les conditions de lavage envisagées. Si la lingette rejoint une collection de spa, nous pouvons parler de cohérence visuelle sans supposer que toutes les pièces doivent avoir la même matière.'),
  ('Nous commençons un projet de poncho bébé par les dimensions et l’usage, avant les motifs.', 'Nous définissons la forme et la couverture', 'L’âge visé est une information utile, mais nous souhaitons aussi les mesures finies. Décrivez la capuche, l’ouverture et la couverture que vous recherchez. Nous pouvons ensuite parler de composition et d’entretien sur la base d’un modèle mieux défini.', 'Un poncho pour le bain et un poncho pour la plage ne répondent pas forcément au même brief. Présentez-nous votre collection et les pièces à coordonner. Les exigences d’étiquetage ou d’essais du marché de destination doivent concerner le modèle réel ; nous ne les présumons pas à partir d’une image de catégorie.'),
  ('Nous souhaitons préciser l’usage d’un lange bébé avant d’en discuter les couleurs.', 'Nous évitons qu’un nom remplace le cahier des charges', 'Le terme lange peut désigner différents formats textiles. Nous vous proposons de décrire le produit attendu, ses dimensions finies et sa composition. Les motifs et références de couleur viennent compléter cette base. Si plusieurs formats sont prévus, indiquez chacun avec sa quantité.', 'Nous souhaitons aussi parler des instructions et de l’étiquetage pour votre marché. Une description de tissu ne nous permet pas d’affirmer une sécurité particulière pour le sommeil. L’usage final, l’entretien et les exigences applicables doivent être examinés avec les spécifications du produit avant toute commande.'),
  ('Nous ne traitons pas une gigoteuse bébé comme un simple accessoire de literie.', 'Nous plaçons le modèle final au centre de l’échange', 'Pour une gigoteuse, nous vous demandons l’âge et les tailles visés, la saison et les fermetures souhaitées. Nous voulons comprendre la construction envisagée plutôt qu’attribuer un indice thermique à partir d’une photographie.', 'La performance thermique, l’ajustement, l’étiquetage et les essais de sécurité doivent être vérifiés pour le modèle final et le marché de destination. Nous ne publions pas de valeur TOG ou de certification supposée. Indiquez les exigences à satisfaire afin que notre discussion porte sur des spécifications documentées et les étapes à envisager.'),
  ('Nous abordons le doudou par ses détails textiles et la conception de la pièce finie.', 'Nous regardons au-delà de l’apparence', 'Nous souhaitons connaître les dimensions, le tissu et les éléments ajoutés au doudou. Une image montre une direction esthétique, mais elle ne remplace pas la description des coutures, fixations ou de l’âge prévu. Nous vous invitons à inclure ces informations dès votre première demande.', 'Le marché de destination et l’étiquetage comptent également. Les évaluations de sécurité applicables doivent concerner le modèle réel, et non un nom de catégorie. Nous pouvons discuter des couleurs tout en conservant ces exigences dans le brief ; les quantités doivent distinguer les variantes que vous envisagez.')
 ],
 'de':[
  ('Für uns beginnt Musselin-Bettwäsche mit der gewünschten Haptik, nicht mit einem Stoffnamen.', 'Wir möchten den Charakter des Gewebes verstehen', 'Wenn Sie uns eine Musselin-Kollektion beschreiben, interessiert uns zunächst das gewünschte Gefühl auf dem Bett. Ein leicht wirkendes Gewebe und ein mehrlagiger Aufbau führen zu unterschiedlichen Anforderungen. Deshalb möchten wir Zusammensetzung, Lagenzahl und Fertigmaße gemeinsam festhalten.', 'Auch das Waschen gehört für uns in diese Diskussion. Die vereinbarten Maße sollten zum erwarteten Einlaufverhalten und zur Pflegeanleitung passen. Für eine abgestimmte Kollektion nennen Sie uns bitte auch Kissenmaße und Farbreferenzen. So können wir über die gesamte Bettwäsche sprechen statt nur über einen einzelnen Bezug.'),
  ('Wir beginnen bei einem Spannbettlaken mit der Matratze, auf die es passen soll.', 'Wir fragen auch nach der Matratzenhöhe', 'Breite und Länge beschreiben die gewünschte Passform noch nicht vollständig. Wir möchten auch die Höhe, einen möglichen Topper und die Anordnung des Gummizugs verstehen. Konkrete Maße helfen uns mehr als eine Größenbezeichnung wie Doppelbett.', 'Wir möchten Material und Fertigmaße festlegen und anschließend das Verhalten nach dem Waschen besprechen. Wenn das Laken mit Bettbezügen kombiniert werden soll, nennen Sie uns die dazugehörigen Farben. Eine Aufteilung der Mengen nach Größe und Farbe macht Ihre geplante Kollektion für die Anfrage nachvollziehbar.'),
  ('Wir betrachten den Bettbezug als verbindendes Element einer Bettwäschekollektion.', 'Für uns gehört der Verschluss zum Entwurf', 'Material und Farbe geben die Richtung vor; die praktischen Details möchten wir ebenfalls festhalten. Dazu gehören die Bettdeckenmaße, die Position der Öffnung und der gewünschte Verschluss. Beschreiben Sie uns, ob die Kollektion für Zuhause oder für Hotels gedacht ist.', 'Kissenbezüge möchten wir möglichst im selben Gespräch berücksichtigen. Maße, Kantenverarbeitung und Stückzahlen bestimmen, was ein Set enthalten soll. Ein Referenzbild hilft bei der Gestaltung, ersetzt aber keine schriftliche Beschreibung von Material, Farbe und Verarbeitung als Grundlage der Angebotsanfrage.'),
  ('Für uns ist ein Bademantel ein Kleidungsstück für einen konkreten Nutzer und Einsatzort.', 'Wir sprechen über Schnitt und Größen', 'Ein Spa-Bademantel und ein Modell für Zuhause können trotz ähnlichem Stoff unterschiedliche Formen benötigen. Wir möchten Größenbereich, Kragen oder Kapuze sowie Gürteldetails besprechen. Das Stoffgewicht ist dabei ein Bestandteil des Entwurfs, nicht seine vollständige Beschreibung.', 'Für Hotelprojekte interessieren uns auch Waschbedingungen und Kennzeichnung. Wenn Sie eine Stickerei wünschen, nennen Sie die Position und teilen Sie eine geeignete Grafikvorlage. Wir möchten die Mengen nach Größe aufgeteilt sehen, damit sich die einzelnen Varianten klar in der Anfrage wiederfinden.'),
  ('Wir möchten zuerst verstehen, welche Aufgabe ein Handtuch in Ihrem Sortiment erfüllen soll.', 'Wir unterscheiden Format, Gewicht und Nutzung', 'Handtücher für Hände, Bad oder Spa müssen nicht dieselbe Spezifikation haben. Wir fragen nach Maßen und Mengen je Format und möchten danach Zusammensetzung, GSM und Farben besprechen. So erkennen wir, wie die einzelnen Teile Ihres Sortiments zusammengehören.', 'Die Pflegebedingungen gehören für uns ebenfalls dazu. Hotelwäsche und Waschen im Haushalt können unterschiedliche Prioritäten setzen. Ein höheres Stoffgewicht ist nicht automatisch für jedes Projekt passend. Beschreiben Sie die gewünschte Haptik, die Anforderungen an Saugfähigkeit und Trocknung sowie Bordüren oder Kennzeichnungen.'),
  ('Wir besprechen einen Saunakilt zuerst über Passform und gewünschte Abdeckung.', 'Wir klären Länge, Umfang und Verschluss', 'Bevor wir auf den Stoff eingehen, möchten wir Länge, Taillenumfang und Verschluss verstehen. Erzählen Sie uns vom vorgesehenen Sauna- oder Spa-Einsatz. Statt eine Einheitsgröße vorauszusetzen, möchten wir die tatsächlich benötigten Maße festhalten.', 'Danach besprechen wir Stoffgewicht, Anforderungen an die Saugfähigkeit und Waschbedingungen. Teilen Sie uns mit, ob Sie ein Unisex-Modell oder mehrere Varianten planen. Diese Aufteilung verbindet jede Menge mit einem klar beschriebenen Format und verhindert, dass ein Bild die Maße ersetzen soll.'),
  ('Wir sehen ein Spa-Stirnband als funktionalen Teil einer Behandlung.', 'Wir fragen nach dem Sitz während der Anwendung', 'Breite, Kopfumfang und Befestigung geben unserer Diskussion eine konkrete Grundlage. Wünschen Sie eine elastische Passform oder einen verstellbaren Verschluss? Beschreiben Sie die Behandlung und die vorgesehenen Nutzer, damit wir zuerst über die Funktion sprechen können.', 'Für eine Spa-Kollektion können wir anschließend die optische Abstimmung mit Handtüchern und Kilts besprechen. Nennen Sie Waschbedingungen, Mengen je Farbe und gewünschte Kennzeichnungen. Diese Anforderungen möchten wir neben den gestalterischen Wünschen sichtbar halten.'),
  ('Wir betrachten Abschminktücher über ihre Oberfläche, ihre Maße und den beschriebenen Verwendungszweck.', 'Wir bleiben bei der tatsächlichen Textilspezifikation', 'Ein kleines Tuch benötigt einen anderen Brief als ein Badetuch. Wir möchten Maße, Zusammensetzung und gewünschte Oberflächenstruktur kennen. Aus einem Foto leiten wir keine Hautwirkung oder Reinigungsleistung ab; der vorgesehene Einsatz gehört ausdrücklich in die Anfrage.', 'Verpackung und Pflege sind weitere Punkte, die wir besprechen möchten. Nennen Sie Stückzahlen je Packung, Farben und Waschbedingungen. Für eine gemeinsame Spa-Kollektion können wir die Gestaltung abstimmen, ohne vorauszusetzen, dass jedes Produkt aus demselben Stoff bestehen muss.'),
  ('Wir beginnen einen Baby-Poncho mit Größe und Verwendung, bevor wir über Muster sprechen.', 'Wir möchten Form und Abdeckung festhalten', 'Die Altersgruppe hilft beim Verständnis, ersetzt aber keine Fertigmaße. Beschreiben Sie uns Kapuze, Öffnung und gewünschte Abdeckung. Auf dieser Grundlage möchten wir Material und Pflegehinweise besprechen.', 'Ein Badeponcho und ein Strandponcho können unterschiedliche Anforderungen haben. Erzählen Sie uns von Ihrer Kollektion und den dazugehörigen Produkten. Kennzeichnungs- und Prüfanforderungen des Zielmarktes müssen am tatsächlichen Modell betrachtet werden; ein Kategoriefoto ist für uns kein Nachweis der Konformität.'),
  ('Wir möchten bei Baby-Pucktüchern zuerst die beabsichtigte Verwendung klären.', 'Wir lassen den Produktnamen nicht den Brief ersetzen', 'Unter ähnlichen Bezeichnungen können unterschiedliche textile Formate angeboten werden. Deshalb möchten wir Produktzweck, Fertigmaße und Zusammensetzung ausdrücklich besprechen. Druck- und Farbwünsche ergänzen diese Angaben. Geplante Größen nennen Sie bitte jeweils mit ihrer Menge.', 'Auch Hinweise zur Verwendung und Kennzeichnung für Ihren Markt gehören in das Gespräch. Aus einer Stoffbeschreibung ergeben sich für uns keine Aussagen zur Schlafsicherheit. Verwendung, Pflege und geltende Anforderungen müssen zusammen mit der finalen Produktspezifikation geklärt werden.'),
  ('Wir behandeln einen Baby-Schlafsack nicht wie gewöhnliches Bettzubehör.', 'Wir stellen das endgültige Modell in den Mittelpunkt', 'Für einen Baby-Schlafsack möchten wir Alters- und Größenbereich, Saison und Verschlüsse kennen. Uns geht es um den vorgesehenen Aufbau, nicht darum, einem Foto einen Wärmewert zuzuordnen.', 'Wärmeleistung, Passform, Kennzeichnung und Sicherheitsprüfungen müssen für Endprodukt und Zielmarkt verifiziert werden. Wir veröffentlichen keinen angenommenen TOG-Wert und kein unbelegtes Zertifikat. Beschreiben Sie die Anforderungen, die Ihr Projekt erfüllen muss, damit wir über dokumentierte Spezifikationen und die nächsten Schritte sprechen können.'),
  ('Wir besprechen ein Baby-Schmusetuch über seine textilen Details und den fertigen Entwurf.', 'Wir fragen nach mehr als dem Aussehen', 'Maße, Gewebe und angebrachte Elemente möchten wir in der Anfrage erkennen können. Ein Referenzbild zeigt eine Gestaltungsidee, ersetzt aber keine Beschreibung von Nähten, Befestigungen oder vorgesehenem Alter. Diese Angaben gehören für uns an den Anfang des Gesprächs.', 'Auch Zielmarkt und Kennzeichnung sind wichtig. Geltende Sicherheitsbewertungen müssen sich auf den tatsächlichen Entwurf beziehen, nicht auf einen allgemeinen Kategorienamen. Farben können wir parallel besprechen; die Mengen sollten die einzelnen geplanten Varianten unterscheiden.')
 ],
 'es':[
  ('Para nosotros, una funda nórdica de muselina empieza por la textura que quiere conseguir.', 'Queremos entender el tacto de su colección', 'Cuando nos presenta una colección de muselina, queremos saber cómo imagina el tejido sobre la cama. Un aspecto ligero y una construcción de varias capas plantean fichas distintas. Por eso proponemos concretar composición, número de capas y medidas finales antes de hablar solo de colores.', 'También queremos considerar el lavado. Las medidas acordadas deben tener sentido junto con el encogimiento previsto y los cuidados. Si la funda forma parte de un conjunto, compártanos las medidas de las almohadas y las referencias de color. Así podremos conversar sobre toda la colección.'),
  ('Empezamos una sábana bajera por el colchón al que debe ajustarse.', 'También nos interesa la altura del colchón', 'El ancho y el largo no describen por completo el ajuste. Queremos conocer la altura, si habrá un sobrecolchón y cómo desea colocar el elástico. Esas medidas nos ayudan más que una etiqueta general como cama doble.', 'Proponemos acordar composición y dimensiones y después comentar el comportamiento tras el lavado. Si la sábana acompaña a una funda nórdica, indíquenos los colores que quiere coordinar. Las cantidades por tamaño y color permiten entender mejor el conjunto que está preparando.'),
  ('Vemos la funda nórdica como una pieza que une su colección de ropa de cama.', 'Para nosotros, el cierre también forma parte del diseño', 'Tejido y color marcan la dirección, pero queremos recoger los detalles prácticos. Medidas del edredón, posición de la abertura y tipo de cierre deben aparecer en la ficha. Cuéntenos si el proyecto es para el hogar o para hoteles, porque las prioridades de uso pueden cambiar.', 'Preferimos comentar las fundas de almohada en la misma conversación. Sus medidas, acabados y cantidades definen lo que debe incluir el conjunto. Una imagen ayuda a explicar el estilo; queremos además una descripción escrita de material, color y confección como base de la consulta.'),
  ('Para nosotros, un albornoz se define alrededor de quien lo llevará y de dónde lo usará.', 'Hablamos de tallas y forma antes de resumir el tejido', 'Un albornoz de spa y uno de hogar pueden necesitar cortes diferentes aunque compartan material. Queremos conocer las tallas, el cuello o la capucha y los detalles del cinturón. El gramaje forma parte de esa conversación, junto con el tacto y las expectativas de secado.', 'En proyectos de hotel también nos interesa el lavado y la identificación. Si desea bordado, indique su posición y comparta una referencia gráfica adecuada. Le proponemos separar las cantidades por talla para que cada variante quede clara en la solicitud.'),
  ('Queremos saber qué espera de una toalla antes de centrarnos en su gramaje.', 'Distinguimos formatos, peso y uso', 'Una toalla de manos, una de baño y una de spa no tienen por qué compartir ficha. Pedimos medidas y cantidades para cada formato y después comentamos composición, GSM y colores. Así podemos entender cómo encajan las piezas de su gama.', 'Los cuidados también forman parte del proyecto. El lavado de un hotel puede plantear prioridades diferentes al doméstico. Más gramaje no es una respuesta universal. Cuéntenos el tacto que busca, sus requisitos de absorción y secado y los bordes o detalles de identificación que desea incluir.'),
  ('Abordamos un pareo de sauna por su ajuste y la cobertura que necesita.', 'Queremos concretar longitud y cierre', 'Antes del tejido, nos interesa conocer longitud, contorno de cintura y cierre. Describa el uso previsto en sauna o spa. Preferimos trabajar con medidas concretas en lugar de dar por hecho que una talla única responderá a todas las necesidades.', 'Después comentamos gramaje, absorción y condiciones de lavado. Díganos si plantea un modelo unisex o varias variantes. Esta separación permite relacionar cada cantidad con un formato y evita que una fotografía sustituya las medidas del producto.'),
  ('Vemos una diadema de spa como una parte funcional del tratamiento.', 'Preguntamos cómo debe mantenerse en su sitio', 'Ancho, contorno de cabeza y sujeción ofrecen una base concreta para conversar. ¿Prefiere ajuste elástico o cierre regulable? Queremos conocer el tratamiento y la persona que utilizará la diadema antes de centrarnos en su color.', 'Para una colección de spa podemos comentar después la coordinación con toallas y pareos. Comparta los cuidados, las cantidades por color y los detalles de identificación. Queremos mantener visibles esas necesidades funcionales junto a las preferencias decorativas.'),
  ('Comentamos las toallitas desmaquillantes a partir de su superficie, tamaño y uso previsto.', 'Nos centramos en la ficha real del tejido', 'Una pieza pequeña no se describe como una toalla de baño. Queremos conocer medidas, composición y textura deseada. No deducimos beneficios para la piel ni rendimiento de limpieza de una imagen; el uso debe quedar explícito en la consulta.', 'También queremos hablar del embalaje y el cuidado. Indique unidades por paquete, colores y condiciones de lavado. Si las toallitas forman parte de una gama de spa, podemos comentar la coherencia visual sin asumir que todos sus productos necesitan el mismo tejido.'),
  ('Empezamos un poncho para bebé por las medidas y el uso, antes de comentar los estampados.', 'Queremos definir forma y cobertura', 'La edad prevista ayuda, pero también pedimos dimensiones finales. Describa capucha, abertura y cobertura. Con esos elementos podremos conversar sobre material y cuidados con una ficha más concreta.', 'Un poncho de baño y otro de playa pueden plantear necesidades diferentes. Cuéntenos su colección y los productos que quiere coordinar. Los requisitos de etiquetado o ensayos del mercado de destino deben revisarse para el modelo real; no consideramos una imagen de categoría como prueba de conformidad.'),
  ('Queremos aclarar el uso de una muselina para bebé antes de hablar de su color.', 'El nombre del producto no sustituye la ficha', 'Una misma denominación puede incluir formatos textiles distintos. Por eso proponemos describir finalidad, medidas y composición. Los estampados y colores completan esa base. Si prevé varios tamaños, indique cada uno con su cantidad.', 'También queremos comentar instrucciones y etiquetado para su mercado. Una descripción del tejido no permite afirmar una seguridad particular para el sueño. Uso final, cuidados y requisitos aplicables deben considerarse junto con las especificaciones antes de acordar un pedido.'),
  ('No tratamos un saco de dormir para bebé como un accesorio corriente de cama.', 'Ponemos el modelo final en el centro de la conversación', 'Para un saco de dormir pedimos edades, tallas, temporada y cierres. Queremos entender la construcción prevista en vez de atribuir un valor térmico a partir de una fotografía.', 'Rendimiento térmico, ajuste, etiquetado y ensayos de seguridad deben verificarse para el producto final y el mercado de destino. No publicamos un valor TOG ni una certificación supuestos. Indique los requisitos que debe cumplir su proyecto para conversar sobre especificaciones documentadas y próximos pasos.'),
  ('Abordamos un dou dou a partir de sus detalles textiles y del diseño terminado.', 'Queremos conocer algo más que su apariencia', 'Nos interesa conocer dimensiones, tejido y elementos añadidos. Una referencia visual muestra el estilo, pero no sustituye una descripción de costuras, uniones o edad prevista. Le invitamos a incluir esos detalles desde la primera consulta.', 'El mercado de destino y el etiquetado también cuentan. Las evaluaciones de seguridad aplicables deben corresponder al diseño real, no a un nombre de categoría. Podemos hablar de colores manteniendo esas exigencias en la ficha; las cantidades deben distinguir cada variante que piensa pedir.')
 ]
}

GROUPS={
 'en':[
  'We see bedding as a connected collection. A muslin cover sets one direction for texture; a fitted sheet asks a different question about mattress fit. We want to discuss those differences with you, then agree how the colours, pillowcases and sizes will belong together.',
  'We approach hotel and spa textiles through the way each piece will be used. Towels, robes and treatment accessories do not share one universal specification. We want to hear about guest use and laundering before discussing dimensions, weight and the finishing details of your range.',
  'For us, a baby range needs a clear brief for every design. A poncho, a swaddle and a sleeping bag serve different purposes. We discuss each product on its own terms and keep the intended age, instructions and destination-market requirements visible in the conversation.'
 ],
 'fr':[
  'Nous voyons le linge de lit comme un ensemble de pièces liées. La gaze de coton apporte une direction de texture, tandis que le drap-housse pose une question d’ajustement au matelas. Nous souhaitons parler de ces différences avec vous, puis définir l’accord des couleurs, taies et dimensions.',
  'Nous abordons les textiles d’hôtel et de spa par l’usage de chaque pièce. Serviettes, peignoirs et accessoires de soin ne relèvent pas d’une spécification unique. Nous souhaitons connaître les conditions de lavage et l’utilisation avant de discuter mesures, grammage et finitions.',
  'Pour nous, une gamme bébé demande un cahier des charges propre à chaque modèle. Un poncho, un lange et une gigoteuse ont des fonctions différentes. Nous discutons chaque produit séparément en gardant visibles l’âge prévu, les instructions et les exigences du marché de destination.'
 ],
 'de':[
  'Wir sehen Bettwäsche als zusammengehörige Kollektion. Musselin gibt eine Richtung für die Haptik vor; beim Spannbettlaken steht die Matratzenpassform im Mittelpunkt. Diese Unterschiede möchten wir mit Ihnen besprechen und anschließend Farben, Kissenbezüge und Größen aufeinander beziehen.',
  'Wir betrachten Hotel- und Spa-Textilien über den Einsatz jeder einzelnen Komponente. Handtücher, Bademäntel und Behandlungszubehör haben keine gemeinsame Universalspezifikation. Wir möchten Nutzung und Waschbedingungen verstehen, bevor wir über Maße, Gewicht und Verarbeitung sprechen.',
  'Für uns benötigt jedes Modell einer Babykollektion einen klaren Brief. Poncho, Pucktuch und Schlafsack erfüllen unterschiedliche Zwecke. Wir besprechen sie einzeln und behalten vorgesehenes Alter, Gebrauchshinweise und Anforderungen des Zielmarktes im Blick.'
 ],
 'es':[
  'Vemos la ropa de cama como un conjunto conectado. La muselina marca una textura; la sábana bajera plantea el ajuste al colchón. Queremos comentar esas diferencias y después acordar cómo se relacionan colores, almohadas y medidas dentro de su colección.',
  'Abordamos los textiles de hotel y spa según el uso de cada pieza. Toallas, albornoces y accesorios de tratamiento no comparten una especificación universal. Queremos entender utilización y lavado antes de comentar medidas, gramaje y acabados.',
  'Para nosotros, cada diseño de una gama de bebé necesita una ficha clara. Ponchos, muselinas y sacos de dormir tienen finalidades distintas. Los comentamos por separado, manteniendo presentes edad prevista, instrucciones y requisitos del mercado de destino.'
 ]}

CORE={
 'en':dict(intro='We bring home, hotel, spa and baby textiles to international buyers from Denizli, Türkiye. Tell us about the collection you want to build; we want to understand the product before discussing a quote.',about='We are TVS Textile, based in Denizli, Türkiye. We work with international buyers on home, hospitality and baby textile enquiries. We use this website to show the products we can discuss with you and the details we need to understand your project.',about_more='We want our first conversation to be useful. Tell us who the product is for, which sizes and materials you have in mind and where the order is intended to go. Where a specification or document needs confirmation, we prefer to make that question explicit rather than present an assumption as a finished product fact.',contact='We would like to hear what you are planning. Send us the product names, quantities and destination, together with the details that matter most to your project. We can then discuss the questions that need to be answered before a quotation.',brief='We start with your intended use, then talk about materials, measurements and quantities. Share the details you already know and identify the decisions you still want to discuss.',by='Company perspective: TVS Textile',product_heading='How we approach this product',check='What we want to clarify with you',group_heading='Our view of this collection'),
 'fr':dict(intro='Depuis Denizli, en Türkiye, nous échangeons avec les acheteurs internationaux sur le linge de maison, les textiles d’hôtel, de spa et de bébé. Présentez-nous votre collection ; nous souhaitons comprendre le produit avant de parler de devis.',about='Nous sommes TVS Textile, à Denizli, en Türkiye. Nous échangeons avec des acheteurs internationaux sur leurs projets de linge de maison, d’hôtellerie et de bébé. Ce site présente les produits dont nous pouvons discuter et les informations utiles pour comprendre votre projet.',about_more='Nous souhaitons que le premier échange soit concret. Dites-nous à qui le produit est destiné, quelles matières et dimensions vous envisagez et vers quel marché il doit aller. Si une spécification ou un document reste à confirmer, nous préférons le signaler plutôt que présenter une hypothèse comme un fait établi.',contact='Nous souhaitons connaître votre projet. Envoyez-nous les produits, quantités et destination, ainsi que les détails les plus importants pour vous. Nous pourrons ensuite discuter des points à préciser avant un devis.',brief='Nous partons de l’usage prévu, puis discutons matières, mesures et quantités. Partagez ce que vous savez déjà et les choix que vous souhaitez encore examiner avec nous.',by='Point de vue de l’entreprise : TVS Textile',product_heading='Notre approche de ce produit',check='Les points que nous souhaitons préciser ensemble',group_heading='Notre regard sur cette collection'),
 'de':dict(intro='Von Denizli in Türkiye aus sprechen wir mit internationalen Einkäufern über Heim-, Hotel-, Spa- und Babytextilien. Erzählen Sie uns von Ihrer geplanten Kollektion; wir möchten das Produkt verstehen, bevor wir über ein Angebot sprechen.',about='Wir sind TVS Textile aus Denizli in Türkiye. Wir sprechen mit internationalen Einkäufern über Heimtextilien, Hotelbedarf und Babykollektionen. Auf dieser Website zeigen wir die Produktbereiche, die wir mit Ihnen besprechen können, und die Angaben, die uns helfen, Ihr Projekt zu verstehen.',about_more='Wir möchten das erste Gespräch konkret gestalten. Nennen Sie Nutzer, gewünschte Materialien und Maße sowie das Zielland. Wenn eine Spezifikation oder ein Dokument noch bestätigt werden muss, sprechen wir diese Frage lieber offen an, als eine Annahme als feststehende Produkteigenschaft darzustellen.',contact='Wir möchten erfahren, was Sie planen. Teilen Sie uns Produkte, Mengen und Zielland sowie die für Sie wichtigen Details mit. Anschließend können wir die Fragen besprechen, die vor einem Angebot zu klären sind.',brief='Wir beginnen mit der Verwendung und sprechen dann über Materialien, Maße und Mengen. Teilen Sie uns mit, was bereits feststeht und welche Entscheidungen Sie noch mit uns besprechen möchten.',by='Unternehmensperspektive: TVS Textile',product_heading='Unser Blick auf dieses Produkt',check='Was wir gemeinsam klären möchten',group_heading='Unser Blick auf diese Kollektion'),
 'es':dict(intro='Desde Denizli, Türkiye, conversamos con compradores internacionales sobre textiles de hogar, hotel, spa y bebé. Cuéntenos la colección que quiere preparar; queremos entender el producto antes de hablar de un presupuesto.',about='Somos TVS Textile, en Denizli, Türkiye. Conversamos con compradores internacionales sobre proyectos de hogar, hostelería y bebé. En esta web mostramos los productos que podemos comentar con usted y la información que nos ayuda a entender su proyecto.',about_more='Queremos que la primera conversación sea concreta. Cuéntenos a quién se dirige el producto, qué materiales y medidas prevé y cuál es su destino. Si falta confirmar una especificación o documento, preferimos plantear esa pregunta en lugar de presentar una suposición como un dato del producto.',contact='Queremos conocer lo que está preparando. Envíenos productos, cantidades y destino, junto con los detalles que más importan para su proyecto. Después podremos comentar qué falta aclarar antes de un presupuesto.',brief='Empezamos por el uso previsto y después comentamos materiales, medidas y cantidades. Comparta lo que ya sabe y las decisiones que todavía quiere hablar con nosotros.',by='Perspectiva de la empresa: TVS Textile',product_heading='Nuestra visión de este producto',check='Lo que queremos concretar juntos',group_heading='Nuestra visión de esta colección')
}

OVERVIEW={
 'en':'We organise our textiles into three collections so you can begin with the products relevant to your project. Bedding, hospitality accessories and baby products ask different questions; we want to discuss each range in its own context.',
 'fr':'Nous présentons nos textiles en trois collections pour vous aider à commencer par les produits de votre projet. Literie, accessoires d’hôtellerie et articles bébé demandent des échanges différents ; nous souhaitons aborder chaque gamme dans son contexte.',
 'de':'Wir gliedern unsere Textilien in drei Kollektionen, damit Sie mit den für Ihr Projekt passenden Produkten beginnen können. Bettwäsche, Hotelzubehör und Babyprodukte stellen unterschiedliche Fragen, die wir im jeweiligen Zusammenhang besprechen möchten.',
 'es':'Organizamos nuestros textiles en tres colecciones para que pueda empezar por los productos de su proyecto. Ropa de cama, accesorios de hotel y artículos de bebé plantean preguntas diferentes; queremos comentar cada gama en su propio contexto.'
}
META={
 'en':dict(products='We manufacture bedding, hotel, spa and baby textiles in Denizli. Explore our collections and tell us the products your business needs.',guide='We explain how we discuss textile briefs: use, materials, sizes, samples and delivery responsibilities. Read our guide for international buyers.',contact='Tell us about your textile project. We welcome enquiries for bedding, hotel, spa and baby products from our own factory in Denizli.',about='We founded TVS Textile in 2021 and manufacture in our own factory in Denizli, Türkiye. Discover our product range and target markets.'),
 'fr':dict(products='Nous fabriquons du linge de lit et des textiles hôtel, spa et bébé à Denizli. Découvrez nos collections et présentez-nous votre projet.',guide='Nous expliquons notre approche des projets textiles : usage, matières, dimensions, échantillons et livraison. Lisez notre guide d’achat.',contact='Présentez-nous votre projet textile. Depuis notre usine à Denizli, nous échangeons sur vos besoins de linge de lit, hôtel, spa et bébé.',about='Nous avons créé TVS Textile en 2021 et fabriquons dans notre propre usine à Denizli. Découvrez notre gamme et nos marchés cibles.'),
 'de':dict(products='Wir fertigen Bettwäsche, Hotel-, Spa- und Babytextilien in Denizli. Entdecken Sie unsere Kollektionen und erzählen Sie uns von Ihrem Projekt.',guide='Wir erklären unseren Ansatz für Textilprojekte: Verwendung, Material, Maße, Muster und Lieferung. Lesen Sie unseren Einkaufsleitfaden.',contact='Erzählen Sie uns von Ihrem Textilprojekt. Wir freuen uns über Anfragen zu Bettwäsche, Hotel-, Spa- und Babytextilien aus unserer Fabrik in Denizli.',about='Wir haben TVS Textile 2021 gegründet und fertigen in unserer eigenen Fabrik in Denizli. Lernen Sie unser Sortiment und unsere Zielmärkte kennen.'),
 'es':dict(products='Fabricamos ropa de cama y textiles de hotel, spa y bebé en Denizli. Explore nuestras colecciones y cuéntenos los productos que necesita.',guide='Explicamos cómo comentamos los proyectos textiles: uso, materiales, medidas, muestras y entrega. Lea nuestra guía para compradores.',contact='Cuéntenos su proyecto textil. Desde nuestra propia fábrica de Denizli conversamos sobre ropa de cama y textiles de hotel, spa y bebé.',about='Fundamos TVS Textile en 2021 y fabricamos en nuestra propia planta de Denizli. Conozca nuestra gama y nuestros mercados objetivo.')
}

GUIDE={
 'en':[
  ('We begin with the use, not with a photograph','When you contact us, we want to know whether you are planning a retail bedding collection, hotel replenishment or a baby range. A reference image is useful for style, but it does not tell us the dimensions, fabric or care conditions. We prefer to separate what you like visually from what the product needs to do.'),
  ('We turn the enquiry into specific questions','We ask you to break the quantities down by size and colour. We also want the composition, relevant fabric weight and any finishing or packaging preferences. If some decisions are still open, say so: we can discuss them instead of letting a vague description stand in for an agreed specification.'),
  ('We keep document requests tied to the actual product','Tell us which samples, certificates or test reports your market requires. We want those requirements to refer to the final design and material. A category image is not a compliance document, and we do not use it as one. Availability and scope need to be confirmed for the project.'),
  ('We want the next step to be clear in writing','Before an order is agreed, we want quantities, specifications, sample approval, timing and delivery responsibilities to be explicit. Minimum quantities and commercial conditions depend on the project; we do not give a universal promise on this page. Send us your destination and target schedule so the discussion has a concrete basis.')
 ],
 'fr':[
  ('Nous partons de l’usage, pas d’une photographie','Dès le premier contact, nous souhaitons savoir si vous préparez une gamme de literie, un réassort hôtelier ou une collection bébé. Une image aide à parler de style ; elle ne précise ni dimensions, ni matière, ni lavage. Nous distinguons donc la direction esthétique des besoins réels du produit.'),
  ('Nous transformons la demande en questions précises','Nous vous invitons à répartir les quantités par taille et couleur et à indiquer composition, grammage pertinent et finitions. Si certains choix restent ouverts, dites-le-nous. Nous préférons en discuter plutôt que laisser une description vague remplacer des spécifications convenues.'),
  ('Nous relions les documents au produit réel','Précisez les échantillons, certificats ou rapports exigés par votre marché. Nous souhaitons examiner ces demandes pour le modèle et la matière définitifs. Une photographie de catégorie n’est pas un document de conformité. Disponibilité et portée doivent être confirmées pour votre projet.'),
  ('Nous souhaitons une prochaine étape écrite et claire','Avant de convenir d’une commande, nous voulons préciser quantités, spécifications, validation des échantillons, calendrier et responsabilités de livraison. Conditions commerciales et quantités minimales dépendent du projet. Votre destination et votre calendrier donnent une base concrète à l’échange.')
 ],
 'de':[
  ('Wir beginnen mit der Nutzung statt mit einem Foto','Beim ersten Kontakt möchten wir wissen, ob Sie eine Bettwäschekollektion, Hotelnachbestellungen oder ein Babysortiment planen. Ein Bild hilft bei der Gestaltung, beschreibt aber weder Maße noch Material oder Waschbedingungen. Wir trennen daher den gewünschten Stil von den tatsächlichen Produktanforderungen.'),
  ('Wir machen aus der Anfrage konkrete Fragen','Wir möchten Mengen nach Größe und Farbe, Zusammensetzung, relevantes Stoffgewicht und gewünschte Verarbeitung kennen. Wenn Entscheidungen noch offen sind, sagen Sie uns das bitte. Wir besprechen diese Punkte lieber, als eine unklare Beschreibung als vereinbarte Spezifikation stehenzulassen.'),
  ('Wir beziehen Unterlagen auf das tatsächliche Produkt','Nennen Sie Muster, Zertifikate oder Prüfberichte, die Ihr Markt verlangt. Für uns müssen sie zum endgültigen Modell und Material passen. Ein Kategoriefoto ist kein Konformitätsnachweis. Verfügbarkeit und Geltungsbereich der Dokumente sind für das Projekt zu bestätigen.'),
  ('Wir möchten den nächsten Schritt schriftlich klären','Vor einer Bestellung sollen Mengen, Spezifikationen, Musterfreigabe, Zeitplan und Lieferverantwortung feststehen. Mindestmengen und Konditionen sind projektabhängig; diese Seite gibt keine pauschale Zusage. Zielland und gewünschter Termin helfen, die Diskussion konkret zu führen.')
 ],
 'es':[
  ('Empezamos por el uso, no por una fotografía','En el primer contacto queremos saber si prepara una colección de cama, reposición para hoteles o una gama de bebé. Una imagen ayuda a explicar el estilo, pero no define medidas, material ni lavado. Por eso distinguimos la dirección visual de lo que necesita hacer el producto.'),
  ('Convertimos la consulta en preguntas concretas','Pedimos cantidades por tamaño y color, composición, gramaje pertinente y acabados. Si quedan decisiones abiertas, indíquelo. Preferimos comentarlas a dejar que una descripción imprecisa sustituya las especificaciones acordadas.'),
  ('Relacionamos los documentos con el producto real','Cuéntenos qué muestras, certificados o informes requiere su mercado. Queremos que correspondan al diseño y material definitivos. Una fotografía de categoría no es un documento de conformidad. Disponibilidad y alcance deben confirmarse para el proyecto.'),
  ('Queremos dejar claro el siguiente paso por escrito','Antes de acordar un pedido, queremos concretar cantidades, especificaciones, aprobación de muestras, calendario y responsabilidades de entrega. Mínimos y condiciones dependen del proyecto; no prometemos un valor universal en esta página. Destino y plazo deseado dan una base concreta a la conversación.')
 ]}

FACTS={
 'en':dict(intro='We manufacture home, hotel, spa and baby textiles in our own factory in Denizli, Türkiye. Founded in 2021, we are building relationships with international buyers around clear product briefs.',about='We founded TVS Textile in 2021. We manufacture in our own factory at Akçeşme M. 2605 Sk. No: 40 in Merkezefendi, Denizli. Our product range brings together home textiles, hotel and spa textiles, and baby collections.',markets='We welcome enquiries from France, Germany, the Netherlands, Spain and the United States. These are the markets we are targeting; we want to understand the dimensions, intended use and product requirements of each buyer rather than assume every country needs the same collection.',factory='Our own factory in Denizli',year='Established in 2021',market_heading='The markets we want to connect with',origin='We manufacture in Türkiye',about_heading='We are TVS Textile.<br><em>We make our textiles in Denizli.</em>'),
 'fr':dict(intro='Nous fabriquons du linge de maison et des textiles pour hôtel, spa et bébé dans notre propre usine à Denizli, en Türkiye. Depuis notre création en 2021, nous construisons nos échanges avec les acheteurs internationaux autour de projets clairement définis.',about='Nous avons créé TVS Textile en 2021. Nous fabriquons dans notre propre usine, à Akçeşme M. 2605 Sk. No: 40, Merkezefendi, Denizli. Notre gamme réunit linge de maison, textiles pour hôtel et spa, et collections bébé.',markets='Nous souhaitons échanger avec des acheteurs en France, en Allemagne, aux Pays-Bas, en Espagne et aux États-Unis. Ce sont nos marchés cibles. Nous voulons comprendre leurs dimensions, usages et exigences plutôt que supposer qu’une seule collection convient à tous les pays.',factory='Notre propre usine à Denizli',year='Création en 2021',market_heading='Les marchés avec lesquels nous souhaitons échanger',origin='Nous fabriquons en Türkiye',about_heading='Nous sommes TVS Textile.<br><em>Nous fabriquons à Denizli.</em>'),
 'de':dict(intro='Wir fertigen Heim-, Hotel-, Spa- und Babytextilien in unserer eigenen Fabrik in Denizli, Türkiye. Seit unserer Gründung 2021 möchten wir Beziehungen zu internationalen Einkäufern auf klar beschriebenen Produktprojekten aufbauen.',about='Wir haben TVS Textile 2021 gegründet. Wir produzieren in unserer eigenen Fabrik in Akçeşme M. 2605 Sk. No: 40, Merkezefendi, Denizli. Unser Sortiment umfasst Heimtextilien, Hotel- und Spa-Textilien sowie Babykollektionen.',markets='Wir freuen uns über Anfragen aus Frankreich, Deutschland, den Niederlanden, Spanien und den USA. Das sind unsere Zielmärkte. Wir möchten Maße, Verwendung und Anforderungen jedes Einkäufers verstehen, statt dieselbe Kollektion für jedes Land vorauszusetzen.',factory='Unsere eigene Fabrik in Denizli',year='Gegründet 2021',market_heading='Mit diesen Märkten möchten wir ins Gespräch kommen',origin='Wir fertigen in Türkiye',about_heading='Wir sind TVS Textile.<br><em>Wir produzieren in Denizli.</em>'),
 'es':dict(intro='Fabricamos textiles de hogar, hotel, spa y bebé en nuestra propia fábrica de Denizli, Türkiye. Desde nuestra creación en 2021, buscamos relaciones con compradores internacionales a partir de proyectos bien definidos.',about='Fundamos TVS Textile en 2021. Fabricamos en nuestra propia planta de Akçeşme M. 2605 Sk. No: 40, Merkezefendi, Denizli. Nuestra gama reúne textiles para hogar, hotel y spa, además de colecciones de bebé.',markets='Queremos conversar con compradores de Francia, Alemania, Países Bajos, España y Estados Unidos. Son nuestros mercados objetivo. Nos interesa conocer medidas, usos y requisitos de cada comprador, en lugar de suponer que una misma colección sirve para todos los países.',factory='Nuestra propia fábrica en Denizli',year='Fundada en 2021',market_heading='Los mercados con los que queremos conectar',origin='Fabricamos en Türkiye',about_heading='Somos TVS Textile.<br><em>Fabricamos en Denizli.</em>')
}

def apply_voice(lang,slug,body,items,label_index):
 import re
 from html import escape
 c=CORE[lang];f=FACTS[lang]
 if slug=='products':
  body=re.sub(r'(<section class="page-intro">.*?</h1>)<p>.*?</p>',lambda m:m[1]+'<p>'+escape(OVERVIEW[lang])+'</p>',body,count=1,flags=re.S)
 if slug.startswith('collections/'):
  tail=slug.split('/')[-1];index=next((i for i,it in enumerate(items) if it[0]==tail),None)
  if index is not None:
   lead,heading,p1,p2=PRODUCTS[lang][index]
   body=re.sub(r'(<section class="split-intro">.*?<h1>.*?</h1>)<p>.*?</p>',lambda m:m[1]+'<p>'+escape(lead)+'</p>',body,count=1,flags=re.S)
   body=re.sub(r'(<section class="section product-detail"><div>).*?(</div><aside>)',lambda m:m[1]+'<span class="eyebrow">'+escape(c['product_heading'])+'</span><h2>'+escape(heading)+'</h2><p>'+escape(p1)+'</p><p>'+escape(p2)+'</p>'+m[2],body,count=1,flags=re.S)
  else:
   group=next((it[1] for it in items if ['home-textiles','hotel-spa-textiles','baby-textiles'][it[1]]==tail),None)
   if group is not None:
    body=re.sub(r'(<section class="split-intro">.*?<h1>.*?</h1>)<p>.*?</p>',lambda m:m[1]+'<p>'+escape(GROUPS[lang][group])+'</p>',body,count=1,flags=re.S)
 if slug=='about':
  body=re.sub(r'(<section class="page-intro">.*?<h1>).*?(</h1>)',lambda m:m[1]+f['about_heading']+m[2],body,count=1,flags=re.S)
  body=re.sub(r'(<section class="page-intro">.*?</h1>)<p>.*?</p>',lambda m:m[1]+'<p>'+escape(f['about'])+'</p><p>'+escape(c['about_more'])+'</p>',body,count=1,flags=re.S)
  market=f'<section class="section company-facts"><div><span class="eyebrow">TVS TEXTILE / {FOUNDED}</span><h2>{escape(f["factory"])}</h2><p>{escape(f["year"])}</p></div><div><h3>{escape(f["market_heading"])}</h3><p>{escape(f["markets"])}</p></div></section>'
  body=body.replace('<section class="project-section">',market+'<section class="project-section">',1)
 if slug=='index':
  body=re.sub(r'(<div class="story-copy reveal">.*?</h2>)<p>.*?</p>',lambda m:m[1]+'<p>'+escape(f['about'])+'</p>',body,count=1,flags=re.S)
  badge='<div class="factory-note"><span>'+escape(f['factory'])+'</span><span>'+escape(f['year'])+'</span></div>'
  body=body.replace('<div class="hero-foot">',badge+'<div class="hero-foot">',1)
  steps={
   'en': [('We start with the product','We want to understand the fabric, size and details that will shape your collection.'),('We discuss what remains open','We ask which sample and specification questions you want to resolve before ordering.'),('We clarify the next step','We want the quotation, agreed details and destination to be clear before an order is placed.')],
   'fr': [('Nous partons du produit','Nous souhaitons comprendre les matières, mesures et détails de votre collection.'),('Nous discutons des choix ouverts','Nous demandons quels points de spécification et d’échantillonnage restent à préciser.'),('Nous clarifions la suite','Nous voulons un devis, des détails convenus et une destination clairement définis avant la commande.')],
   'de': [('Wir beginnen beim Produkt','Wir möchten Material, Maße und die Details Ihrer Kollektion verstehen.'),('Wir besprechen offene Fragen','Wir fragen nach den Muster- und Spezifikationspunkten, die noch zu klären sind.'),('Wir klären den nächsten Schritt','Wir möchten Angebot, vereinbarte Details und Zielland vor der Bestellung festhalten.')],
   'es': [('Empezamos por el producto','Queremos entender materiales, medidas y detalles de su colección.'),('Comentamos las decisiones abiertas','Preguntamos qué puntos de muestras y especificaciones quiere concretar.'),('Aclaramos el siguiente paso','Queremos presupuesto, detalles acordados y destino claros antes de un pedido.')]
  }
  rows=iter(steps[lang])
  body=re.sub(r'(<div class="brief-card reveal"><span>.*?</span>)<h3>.*?</h3><p>.*?</p>',lambda m:step_row(m,next(rows)),body,flags=re.S)
 if slug=='sourcing-guide':
  matches=iter(GUIDE[lang])
  body=re.sub(r'(<article class="guide-row reveal"><span>.*?</span><div>)<h2>.*?</h2><p>.*?</p>(</div></article>)',lambda m:guide_row(m,next(matches)),body,flags=re.S)
 if slug=='privacy':
  body=body.replace('so TVS Textile can respond','so we can respond').replace('Contact data</h1>','Contact data</h1>')
 return body

def guide_row(match,copy):
 from html import escape
 return match[1]+'<h2>'+escape(copy[0])+'</h2><p>'+escape(copy[1])+'</p>'+match[2]

def step_row(match,copy):
 from html import escape
 return match[1]+'<h3>'+escape(copy[0])+'</h3><p>'+escape(copy[1])+'</p>'
