"""Buyer-oriented, fact-based product content. No unverified specifications or promises."""
from html import escape
UPDATED='2026-10-06'
DATES={'en':'Content updated: 6 October 2026','fr':'Contenu mis à jour : 6 octobre 2026','de':'Inhalt aktualisiert: 6. Oktober 2026','es':'Contenido actualizado: 6 de octubre de 2026'}
COPY={
 'en':dict(manufacturer='Manufacturer in Türkiye',heading='From our Denizli factory to your product brief',factory='We manufacture in our own factory in Merkezefendi, Denizli. We founded TVS Textile in 2021, and we welcome business enquiries from brands, retailers and hospitality buyers. For this product, we want to agree the actual specification rather than quote from a photograph alone.',spec='What we need to discuss for this product',field='Specification',value='Include in your enquiry',faq='Before you request a quotation',quote='How do we prepare a wholesale enquiry?',answer='Send us the quantity for each size or colour, the destination country and your preferred schedule. Include your reference images and the specifications below. We will discuss the outstanding details with you; minimum quantities, sample availability, prices and lead times need confirmation for your particular project.',next='Plan samples, specifications and delivery terms',title=lambda n:n+' Manufacturer in Turkey | TVS Textile',description=lambda n:n+' from our own Denizli factory. Discuss product specifications, quantities and your wholesale sourcing brief with TVS Textile.'),
 'fr':dict(manufacturer='Fabricant en Turquie',heading='Notre usine à Denizli, votre cahier des charges',factory='Nous fabriquons dans notre propre usine à Merkezefendi, Denizli. TVS Textile a été créée en 2021. Nous souhaitons échanger avec les marques, les boutiques et les acheteurs de l’hôtellerie sur les caractéristiques précises de leurs produits : une photographie ne suffit pas à établir un devis.',spec='Les détails à nous transmettre pour ce produit',field='Point à définir',value='Informations pour votre demande',faq='Avant de demander un devis',quote='Comment préparer une demande pour un achat en gros ?',answer='Présentez les quantités par taille ou couleur, le pays de destination et votre calendrier. Joignez vos références visuelles et les détails ci-dessous. Nous préciserons ensemble les points ouverts. Minimum de commande, disponibilité des échantillons, prix et délais doivent être confirmés pour votre projet.',next='Préparer les échantillons, spécifications et conditions de livraison',title=lambda n:'Fabricant de '+n.lower()+' en Turquie | TVS Textile',description=lambda n:n+' : fabrication dans notre propre usine à Denizli. Échangeons sur les caractéristiques, quantités et besoins de votre achat professionnel.'),
 'de':dict(manufacturer='Hersteller in der Türkei',heading='Unsere Fabrik in Denizli. Ihre Produktspezifikation.',factory='Wir produzieren in unserer eigenen Fabrik in Merkezefendi, Denizli. TVS Textile wurde 2021 gegründet. Mit Marken, Einzelhändlern und Einkäufern aus Hotel und Spa möchten wir die konkreten Produktanforderungen besprechen. Für ein Angebot brauchen wir mehr als ein Kategorienfoto.',spec='Diese Angaben helfen uns bei Ihrer Produktanfrage',field='Spezifikation',value='Angaben für Ihre Anfrage',faq='Vor Ihrer Angebotsanfrage',quote='Welche Angaben brauchen wir für eine Großhandelsanfrage?',answer='Nennen Sie Mengen je Größe oder Farbe, Zielland und gewünschten Zeitplan. Ergänzen Sie Bildvorlagen und die folgenden Spezifikationspunkte. Offene Fragen besprechen wir gemeinsam. Mindestmengen, Musterverfügbarkeit, Preise und Produktionszeiten sind für Ihr konkretes Projekt zu bestätigen.',next='Muster, Spezifikationen und Lieferbedingungen planen',title=lambda n:n+' Hersteller Türkei | TVS Textile',description=lambda n:n+' aus unserer eigenen Fabrik in Denizli. Besprechen Sie Spezifikationen, Mengen und Ihren Textileinkauf mit TVS Textile.'),
 'es':dict(manufacturer='Fabricante en Turquía',heading='De nuestra fábrica en Denizli a su proyecto textil',factory='Fabricamos en nuestra propia planta de Merkezefendi, Denizli. Fundamos TVS Textile en 2021 y queremos trabajar con marcas, comercios y compradores de hostelería a partir de requisitos concretos. Para preparar la consulta de este producto, necesitamos especificaciones además de referencias visuales.',spec='Los detalles que necesitamos para este producto',field='Especificación',value='Información para su consulta',faq='Antes de solicitar un presupuesto',quote='¿Cómo preparar una consulta de compra al por mayor?',answer='Indique cantidades por talla o color, país de destino y calendario deseado. Añada sus referencias visuales y los puntos de especificación siguientes. Comentaremos las decisiones pendientes. Pedido mínimo, disponibilidad de muestras, precios y plazos se confirman para cada proyecto.',next='Preparar muestras, especificaciones y condiciones de entrega',title=lambda n:'Fabricante de '+n.lower()+' en Turquía | TVS Textile',description=lambda n:n+' de nuestra propia fábrica en Denizli. Consulte especificaciones, cantidades y los requisitos de su compra profesional con TVS Textile.')
}

# Each row has distinct specification questions and an original product-specific answer.
DETAILS={
 'en':[
 ('Fabric|Composition and number of gauze layers;Finished size|Duvet and pillowcase measurements;Care brief|Washing conditions and expected finished dimensions after care','How do we specify a muslin duvet cover collection?','We ask you to send a texture reference as well as the dimensions. Tell us which gauze construction and composition you want to discuss, whether pillowcases are included and how the finished set should be packaged. We agree the fabric and care expectations for the actual product before treating the brief as complete.'),
 ('Mattress|Width, length, depth and any topper;Fit|Elastic arrangement and corner construction;Range|Quantities for each mattress size and colour','Can we use bed-size names alone for a fitted-sheet enquiry?','We prefer actual mattress measurements. A label such as queen or king does not tell us the depth of your mattress or whether you use a topper. Send those details alongside the required sheet composition and the fit you want to discuss, so our quotation refers to your particular bedding range.'),
 ('Cover|Duvet width and length;Closure|Opening position and preferred fastening;Set|Pillowcase dimensions and units per set','What should we include in a duvet-cover set brief?','We want to know exactly what belongs in the set. Describe the cover, the number of pillowcases, their dimensions and the closure you prefer. If you are comparing a smooth woven cover with our muslin range, make that distinction in your enquiry so we discuss the right textile construction.'),
 ('Shape|Collar, hood, sleeve and belt preferences;Sizes|Finished robe measurements and quantities by size;Use|Hotel, spa or homewear laundering requirements','How do we describe the bathrobe style we need?','A front and back reference helps us understand the robe shape. Add the collar or hood style, belt details, finished length and size breakdown. If your enquiry includes a logo, send its position and artwork as a requirement to review; we will confirm the relevant finishing options for the project.'),
 ('Dimensions|Separate hand, bath or other towel sizes;Weight|Requested GSM and composition;Finish|Border, colour and identification requirements','What does a towel enquiry need beyond a GSM figure?','We also ask for dimensions, composition, intended use and the finish you expect. Separate each towel size and quantity in your brief. For hotel and spa enquiries, describe the laundering routine and any identifying artwork you want us to review; a weight figure alone leaves those decisions open.'),
 ('Coverage|Finished length and waist range;Fastening|Preferred closure and adjustment;Care|Spa washing conditions and fabric requirement','How do we prepare a sauna-wrap specification?','We start with coverage and adjustment. Give us the intended waist range, finished length and fastening reference, then explain the textile feel you are looking for. If the wraps belong with towels or robes in a spa collection, send the coordinated colour brief and quantities together.'),
 ('Fit|Head circumference range and band width;Construction|Elastic or adjustable fastening reference;Use|Treatment setting and washing routine','Which fit details matter for a spa headband?','We ask for more than a single flat measurement. Describe the head-size range, preferred band width and how you want the band to adjust. A reference showing the fastening is helpful. Include the washing routine and the number of bands required for your spa or retail packs.'),
 ('Cloth|Finished dimensions and surface-texture reference;Care|Composition and intended washing instructions;Pack|Units per pack and presentation','How do we define a makeup-remover cloth pack?','Tell us the size and surface feel you want, together with the intended cleaning and washing routine. We also need the number of cloths per pack and the presentation you would like to discuss. Do not infer a fabric composition or a specific skin-performance claim from the concept photograph.'),
 ('Sizing|Intended age range and finished body measurements;Hood|Shape and construction reference;Collection|Colour, fabric and quantities by size','What do we need to discuss for a baby poncho?','We want the intended size range and actual finished dimensions rather than an age label alone. Include the hood reference, textile composition you require and care brief. Any destination-market testing, labelling and safety documentation must be reviewed against the final poncho design.'),
 ('Shape|Blanket or shaped-wrap format and dimensions;Material|Composition and construction reference;Instructions|Intended use, labels and care requirements','How do we distinguish a blanket enquiry from a shaped swaddle?','Please describe the format explicitly. A square textile and a shaped wrap with fastening need different written briefs. Send a reference, the finished dimensions and intended use. Instructions and any safety or testing requirements need to be agreed for the final product and destination, not assumed from its name.'),
 ('Size|Intended age range and finished measurements;Closure|Zip, shoulder and opening requirements;Verification|Seasonal brief, thermal-rating evidence and market requirements','Can we assume a thermal rating from the sleeping-bag image?','No. Our concept image does not establish a thermal rating, fabric composition or safety-test result. If your range requires a particular rating, include it in the brief together with the intended sizing and fastening. The evidence and applicable requirements must be confirmed for the finished sleeping bag.'),
 ('Design|Cloth dimensions and attached-element reference;Construction|Material and attachment details;Verification|Intended age, labels and relevant safety requirements','What should we review for a baby comforter design?','Send us the cloth shape and a reference for any attached element. We want to discuss material, dimensions and attachment details together. The intended age and destination-market requirements must be reviewed for the actual design; the illustrative bunny photograph is not evidence of an approved product.')
 ],
 'fr':[
 ('Matière|Composition et nombre de couches de gaze;Dimensions|Mesures de la couette et des taies;Entretien|Lavage prévu et dimensions attendues après entretien','Comment définir une housse de couette en gaze de coton ?','Nous souhaitons recevoir une référence de texture avec les mesures. Indiquez la construction de gaze à étudier, les taies incluses et la présentation du lot. Nous voulons convenir de la matière et de l’entretien du produit réel avant de considérer le cahier des charges comme complet.'),
 ('Matelas|Largeur, longueur, hauteur et surmatelas éventuel;Ajustement|Disposition des élastiques et construction des angles;Gamme|Quantités par dimension et couleur','Une appellation de lit suffit-elle pour un drap-housse ?','Nous préférons les mesures du matelas. Une désignation comme queen ou king ne précise ni sa hauteur ni la présence d’un surmatelas. Ajoutez la composition souhaitée et décrivez l’ajustement recherché : notre échange portera ainsi sur votre gamme réelle.'),
 ('Housse|Largeur et longueur de la couette;Fermeture|Position de l’ouverture et fermeture souhaitée;Parure|Dimensions des taies et nombre de pièces','Que doit préciser une demande de parure de lit ?','Nous voulons connaître chaque pièce de la parure : housse, nombre de taies, mesures et fermeture. Si vous comparez une matière lisse avec notre gamme en gaze de coton, précisez-le dans la demande. Cela nous permet de discuter de la construction textile adaptée à votre projet.'),
 ('Coupe|Col, capuche, manches et ceinture;Tailles|Mesures finies et quantités par taille;Usage|Conditions de lavage en hôtel, spa ou à domicile','Comment nous présenter le modèle de peignoir recherché ?','Une vue de face et de dos nous aide à comprendre la coupe. Ajoutez le col ou la capuche, la ceinture, la longueur finie et les quantités par taille. Pour un logo, transmettez le dessin et son emplacement comme exigence à examiner ; les possibilités de finition restent à confirmer.'),
 ('Dimensions|Mesures distinctes pour chaque type de serviette;Grammage|GSM souhaité et composition;Finition|Bordure, couleur et identification','Le grammage suffit-il pour demander des serviettes ?','Nous demandons également les mesures, la composition, l’usage et la finition. Séparez les tailles et quantités. Pour un hôtel ou spa, décrivez le lavage et joignez les éléments d’identification à examiner. Un chiffre de grammage ne précise pas à lui seul ces choix.'),
 ('Couverture|Longueur finie et plage de tour de taille;Fermeture|Référence du réglage souhaité;Entretien|Lavage du spa et matière demandée','Comment préparer une demande de kilt de sauna ?','Nous partons du tour de taille, de la longueur et du réglage souhaité. Ajoutez une référence de fermeture et décrivez la texture recherchée. Si le kilt accompagne peignoirs et serviettes, transmettez le projet de couleurs coordonnées et les quantités de l’ensemble.'),
 ('Ajustement|Plage de tour de tête et largeur;Construction|Référence élastique ou fermeture réglable;Usage|Type de soins et lavage','Quels détails préciser pour un bandeau de spa ?','Une seule mesure à plat ne suffit pas à décrire votre besoin. Indiquez la plage de tour de tête, la largeur et le réglage souhaité. Une référence de fermeture est utile. Ajoutez la routine de lavage et le nombre de bandeaux par lot professionnel ou paquet de vente.'),
 ('Lingette|Dimensions et référence de texture;Entretien|Composition et lavage prévu;Lot|Nombre de pièces et présentation','Comment définir un lot de lingettes démaquillantes ?','Précisez les dimensions et la texture, puis l’usage et le lavage envisagés. Nous souhaitons aussi connaître le nombre de lingettes par lot et leur présentation. Une image conceptuelle ne confirme ni la composition ni une promesse particulière concernant la peau.'),
 ('Taille|Âge prévu et mesures finies du corps;Capuche|Référence de forme et construction;Gamme|Matière, couleurs et quantités par taille','Que préciser pour un poncho bébé ?','Nous demandons la gamme de tailles et les mesures finies, plutôt qu’un âge seul. Joignez une référence de capuche, la composition souhaitée et l’entretien. Essais, étiquetage et documents requis sur le marché de destination doivent correspondre au modèle final.'),
 ('Format|Carré textile ou lange façonné et dimensions;Matière|Composition et référence de construction;Instructions|Usage, étiquettes et entretien','Comment distinguer un carré textile d’un lange façonné ?','Décrivez explicitement le format. Un carré et un modèle façonné avec fermeture appellent des cahiers des charges différents. Envoyez référence, dimensions et usage prévu. Les instructions et exigences d’essais ou de sécurité concernent le produit final et sa destination.'),
 ('Taille|Âge prévu et dimensions finies;Ouverture|Zip, épaules et fermeture;Vérification|Saison, preuve du niveau thermique et exigences du marché','Une photographie confirme-t-elle le niveau thermique d’une gigoteuse ?','Non. Notre visuel conceptuel ne prouve ni niveau thermique, ni composition, ni résultat d’essai. Si votre gamme exige une valeur particulière, indiquez-la avec les tailles et fermetures. Les justificatifs doivent être confirmés pour la gigoteuse effectivement produite.'),
 ('Modèle|Dimensions du tissu et référence des éléments attachés;Construction|Matière et assemblage;Vérification|Âge prévu, étiquettes et exigences de sécurité','Que devons-nous examiner pour un doudou ?','Présentez la forme du tissu et les éventuels éléments attachés. Nous voulons discuter ensemble matière, dimensions et assemblage. L’âge et les exigences du marché s’examinent pour le modèle réel ; le lapin illustratif ne constitue pas la preuve d’un produit approuvé.')
 ],
 'de':[
 ('Stoff|Zusammensetzung und Anzahl der Musselinlagen;Maße|Bettdecken- und Kissenbezugmaße;Pflege|Waschbedingungen und erwartete Maße nach der Pflege','Wie beschreiben Sie die gewünschte Musselin-Bettwäsche?','Senden Sie uns neben den Maßen eine Vorlage für die gewünschte Textur. Nennen Sie Lagenaufbau, Zusammensetzung, enthaltene Kissenbezüge und Verpackungswünsche. Wir möchten Material und Pflegeanforderungen für das tatsächliche Produkt klären, bevor die Spezifikation als vollständig gilt.'),
 ('Matratze|Breite, Länge, Höhe und möglicher Topper;Passform|Gummizug und Eckenkonstruktion;Sortiment|Mengen je Matratzenmaß und Farbe','Reicht eine Bettgrößenbezeichnung für Spannbettlaken?','Wir bevorzugen die tatsächlichen Matratzenmaße. Begriffe wie Queen oder King beschreiben weder Matratzenhöhe noch einen Topper. Ergänzen Sie die gewünschte Zusammensetzung und Passform. So bezieht sich unsere Besprechung auf Ihr konkretes Sortiment.'),
 ('Bezug|Breite und Länge der Bettdecke;Verschluss|Öffnungsposition und gewünschte Verschlussart;Set|Kissenmaße und Stückzahl je Set','Was gehört in die Anfrage für ein Bettwäsche-Set?','Beschreiben Sie jedes Teil: Bettbezug, Anzahl und Maße der Kissenbezüge sowie Verschluss. Wenn Sie einen glatten Stoff mit Musselin vergleichen, nennen Sie diesen Unterschied ausdrücklich. Dann können wir die für Ihr Vorhaben gewünschte Textilkonstruktion besprechen.'),
 ('Schnitt|Kragen, Kapuze, Ärmel und Gürtel;Größen|Fertigmaße und Mengen je Größe;Nutzung|Waschbedingungen für Hotel, Spa oder Zuhause','Wie beschreiben Sie den gewünschten Bademantelschnitt?','Eine Vorder- und Rückansicht hilft uns beim Verständnis. Ergänzen Sie Kragen oder Kapuze, Gürtel, fertige Länge und Größenmengen. Für ein Logo senden Sie Position und Vorlage als zu prüfende Anforderung. Die verfügbaren Verarbeitungsoptionen bestätigen wir für das Projekt.'),
 ('Maße|Separate Maße für jede Handtuchart;Gewicht|Gewünschte GSM und Zusammensetzung;Verarbeitung|Bordüre, Farbe und Kennzeichnung','Welche Angaben brauchen wir außer dem Handtuchgewicht?','Wir fragen auch nach Maßen, Zusammensetzung, Nutzung und Verarbeitung. Teilen Sie Größen und Mengen getrennt auf. Für Hotel und Spa beschreiben Sie die Waschbedingungen und gewünschte Kennzeichnung. Eine GSM-Zahl beantwortet diese Fragen noch nicht.'),
 ('Abdeckung|Fertiglänge und Taillenumfang;Verschluss|Vorlage für Einstellung und Befestigung;Pflege|Spa-Waschbedingungen und Material','Wie bereiten Sie eine Saunakilt-Anfrage vor?','Wir beginnen mit Umfang, Länge und gewünschter Einstellung. Senden Sie eine Verschlussvorlage und beschreiben Sie die Textur. Wenn Kilts zu Handtüchern oder Bademänteln gehören sollen, hilft uns ein gemeinsamer Farbbrief mit den jeweiligen Mengen.'),
 ('Passform|Kopfumfangbereich und Bandbreite;Aufbau|Gummizug oder verstellbarer Verschluss;Nutzung|Behandlungsbereich und Waschablauf','Welche Passformangaben braucht ein Spa-Stirnband?','Ein flaches Einzelmaß beschreibt Ihren Bedarf nicht vollständig. Nennen Sie Kopfumfangbereich, Breite und gewünschte Einstellung. Eine Verschlussvorlage hilft. Ergänzen Sie den Waschablauf und die Zahl der Bänder je Betriebspaket oder Verkaufseinheit.'),
 ('Tuch|Fertigmaße und Oberflächenvorlage;Pflege|Zusammensetzung und Waschvorgaben;Packung|Stückzahl und Präsentation','Wie spezifizieren Sie eine Packung Abschminktücher?','Beschreiben Sie Größe und Oberfläche sowie den vorgesehenen Gebrauch und Waschablauf. Wir möchten auch Stückzahl und Präsentation kennen. Aus dem Konzeptbild dürfen weder eine bestimmte Zusammensetzung noch besondere Aussagen zur Hautwirkung abgeleitet werden.'),
 ('Größe|Vorgesehenes Alter und fertige Körpermaße;Kapuze|Form- und Konstruktionsvorlage;Sortiment|Material, Farben und Größenmengen','Welche Angaben brauchen wir für einen Baby-Poncho?','Wir fragen nach Größenbereich und fertigen Maßen, nicht allein nach einem Alter. Ergänzen Sie Kapuzenvorlage, Materialwunsch und Pflegebrief. Prüfungen, Kennzeichnung und Unterlagen für den Zielmarkt müssen zum endgültigen Poncho passen.'),
 ('Form|Quadratisches Tuch oder geformter Wickel und Maße;Material|Zusammensetzung und Aufbau;Hinweise|Nutzung, Kennzeichnung und Pflege','Wie unterscheiden Sie ein Tuch von einem geformten Puckprodukt?','Beschreiben Sie die Form ausdrücklich. Ein quadratisches Textil und ein Modell mit Verschluss brauchen unterschiedliche Spezifikationen. Senden Sie Vorlage, Maße und vorgesehenen Gebrauch. Hinweise und Prüfanforderungen müssen sich auf das Endprodukt und seinen Zielmarkt beziehen.'),
 ('Größe|Vorgesehenes Alter und fertige Maße;Öffnung|Reißverschluss, Schultern und Verschluss;Nachweis|Saison, Wärmewertnachweis und Marktanforderungen','Belegt das Schlafsackfoto einen bestimmten Wärmewert?','Nein. Unser Konzeptbild bestätigt weder Wärmewert noch Zusammensetzung oder Prüfergebnis. Wenn Sie einen bestimmten Wert benötigen, nennen Sie ihn zusammen mit Größen und Verschlüssen. Nachweise und geltende Anforderungen sind für den fertigen Schlafsack zu bestätigen.'),
 ('Entwurf|Tuchmaße und Vorlage befestigter Elemente;Aufbau|Material und Befestigungsdetails;Nachweis|Alter, Kennzeichnung und Sicherheitsanforderungen','Was prüfen wir bei einem Baby-Schmusetuch-Entwurf?','Senden Sie Tuchform und Vorlagen möglicher befestigter Elemente. Wir möchten Material, Maße und Verbindungen gemeinsam besprechen. Alter und Marktanforderungen werden für den tatsächlichen Entwurf geprüft; das illustrative Hasenbild belegt keine Produktfreigabe.')
 ],
 'es':[
 ('Tejido|Composición y número de capas de muselina;Medidas|Dimensiones del edredón y las fundas de almohada;Cuidados|Lavado y medidas esperadas tras el cuidado','¿Cómo definir una funda nórdica de muselina?','Queremos una referencia de textura además de las medidas. Indique las capas y composición que desea estudiar, las fundas de almohada incluidas y la presentación. Acordaremos tejido y cuidados para el producto real antes de dar la especificación por completa.'),
 ('Colchón|Ancho, largo, altura y sobrecolchón;Ajuste|Elásticos y construcción de esquinas;Gama|Cantidades por medida y color','¿Basta con el nombre del tamaño de cama para una sábana bajera?','Preferimos las medidas reales del colchón. Queen o king no indican su altura ni la presencia de un sobrecolchón. Añada composición y ajuste deseados para que nuestra conversación se refiera a su gama concreta de ropa de cama.'),
 ('Funda|Ancho y largo del edredón;Cierre|Posición de apertura y cierre deseado;Juego|Medidas de almohada y piezas por juego','¿Qué debe incluir la consulta de un juego de cama?','Describa cada pieza: funda nórdica, número y medidas de fundas de almohada y cierre. Si compara un tejido liso con muselina, indíquelo expresamente. Así podremos conversar sobre la construcción textil que desea para su colección.'),
 ('Corte|Cuello, capucha, mangas y cinturón;Tallas|Medidas finales y cantidades por talla;Uso|Lavado en hotel, spa o hogar','¿Cómo presentar el estilo de albornoz que necesita?','Una referencia frontal y posterior nos ayuda a entender el corte. Añada cuello o capucha, cinturón, largo final y cantidades por talla. Si necesita un logo, envíe diseño y posición como requisito a revisar; las opciones de acabado se confirman para el proyecto.'),
 ('Medidas|Dimensiones separadas para cada tipo de toalla;Gramaje|GSM solicitado y composición;Acabado|Cenefa, color e identificación','¿Qué necesita una consulta de toallas además del gramaje?','Pedimos medidas, composición, uso y acabado. Separe cantidades por tamaño. Para hotel y spa, describa el lavado y la identificación que desea revisar. Una cifra de GSM no define por sí sola estas decisiones del producto.'),
 ('Cobertura|Largo final y rango de cintura;Cierre|Referencia de ajuste y sujeción;Cuidados|Lavado del spa y material','¿Cómo preparar una especificación de pareo de sauna?','Empezamos por cintura, largo y ajuste. Comparta una referencia de cierre y la textura deseada. Si el pareo forma parte de una gama con toallas y albornoces, envíe los colores coordinados y las cantidades de cada producto.'),
 ('Ajuste|Rango de contorno de cabeza y ancho;Construcción|Elástico o cierre ajustable;Uso|Tratamiento y rutina de lavado','¿Qué detalles de ajuste necesita una diadema de spa?','Una medida en plano no describe todo el requisito. Indique contorno, ancho y ajuste deseados. Una referencia del cierre ayuda. Añada el lavado previsto y las unidades por lote profesional o paquete de venta.'),
 ('Paño|Medidas finales y referencia de superficie;Cuidados|Composición y lavado previsto;Paquete|Unidades y presentación','¿Cómo definir un paquete de toallitas desmaquillantes?','Explique dimensiones, textura, uso y lavado. También queremos conocer unidades por paquete y presentación. Una fotografía conceptual no confirma composición ni una promesa concreta sobre efectos en la piel.'),
 ('Talla|Edad prevista y medidas finales del cuerpo;Capucha|Referencia de forma y construcción;Gama|Material, colores y cantidades por talla','¿Qué debemos comentar sobre un poncho para bebé?','Solicitamos tallas y medidas finales, además de la edad prevista. Incluya capucha, composición requerida y cuidados. Ensayos, etiquetas y documentación del mercado de destino deben corresponder al modelo final del poncho.'),
 ('Formato|Cuadrado textil o envoltura con forma y medidas;Material|Composición y construcción;Instrucciones|Uso, etiquetas y cuidados','¿Cómo distinguir una muselina cuadrada de una envoltura con forma?','Describa el formato explícitamente. Un cuadrado y un modelo con cierre requieren fichas distintas. Comparta referencia, medidas y uso previsto. Instrucciones y requisitos de ensayo o seguridad se acuerdan para el producto final y su destino.'),
 ('Talla|Edad prevista y medidas finales;Apertura|Cremallera, hombros y cierre;Verificación|Temporada, prueba de valor térmico y requisitos del mercado','¿La imagen del saco confirma un valor térmico?','No. El concepto visual no acredita valor térmico, composición ni resultados de ensayo. Si necesita un valor concreto, indíquelo junto con tallas y cierres. Las pruebas y requisitos aplicables se confirman para el saco de dormir terminado.'),
 ('Diseño|Medidas del paño y referencia de elementos unidos;Construcción|Material y detalles de unión;Verificación|Edad, etiquetas y requisitos de seguridad','¿Qué revisar para un dou dou de bebé?','Envíenos la forma del paño y las referencias de elementos unidos. Queremos tratar material, medidas y uniones conjuntamente. Edad y requisitos del mercado se revisan para el diseño real; el conejo ilustrativo no demuestra la aprobación de un producto.')
 ]}

def enrich_product(lang,slug,title,description,body,items,index,base,local):
 if not slug.startswith('collections/'):return title,description,body
 tail=slug.split('/')[-1];item=next((it for it in items if it[0]==tail),None)
 if item is None:return title,description,body
 c=COPY[lang];name=item[index[lang]];rows,question,answer=DETAILS[lang][items.index(item)]
 table=''.join('<tr><th scope="row">'+escape(row.split('|')[0])+'</th><td>'+escape(row.split('|')[1])+'</td></tr>' for row in rows.split(';'))
 block=f'<section class="section manufacturing-brief" id="product-specifications"><div class="manufacturing-origin"><span class="eyebrow">{c["manufacturer"]}</span><h2>{c["heading"]}</h2><p>{c["factory"]}</p><a class="text-link" href="{base}{local(lang,"about")}">TVS Textile / Denizli ↗</a></div><div><h2>{c["spec"]}</h2><div class="spec-scroll"><table class="product-spec"><thead><tr><th scope="col">{c["field"]}</th><th scope="col">{c["value"]}</th></tr></thead><tbody>{table}</tbody></table></div></div></section><section class="section product-questions"><h2>{c["faq"]}</h2><details open><summary>{escape(question)}</summary><p>{escape(answer)}</p></details><details><summary>{c["quote"]}</summary><p>{c["answer"]}</p></details><a class="text-link" href="{base}{local(lang,"sourcing-guide")}">{c["next"]} ↗</a></section>'
 marker='<section class="section"><h2>'
 if marker not in body:marker='<section class="section seo-context">'
 body=body.replace(marker,block+marker,1)
 return c['title'](name),c['description'](name),body
